### ISSUE TITLE
Wrong service selector in ServiceMonitor 

### ISSUE THREAD

**Issue by Vovcharaa** [hashicorp/vault-helm#1047]
**Describe the bug**
Under certain conditions vault chart does not install correct ServiceMonitor selector.  
When I set values to `server.service.active: false` and `service.ha.enabled: true`, ServiceMonitor is created with selector `vault-active: 'true'` but only service with `vault-internal: true` label exists.

**To Reproduce**
1. Install chart with provided values
2. Wrong ServiceMonitor is created and target is not observable in prometheus

**Expected behavior**
ServiceMonitor is created with correct selector

**Environment**
* Kubernetes version: 1.28
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
* vault-helm version: 0.28.0

Chart values:

```yaml
server:
  enabled: true
  service:
    type: NodePort
    active:
      enabled: false
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: false
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        # Enable unauthenticated metrics access (necessary for Prometheus Operator)
        telemetry {
         unauthenticated_metrics_access = "true"
        }
      }
      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }

serverTelemetry:
  serviceMonitor:
    enabled: true
    selectors: 
      release: kube-prometheus-stack
```
