### ISSUE TITLE
Split Server Service Annotations Between Internal & Not

### ISSUE THREAD

**Issue by rfpludwick** [hashicorp/vault-helm#1087]
**Is your feature request related to a problem? Please describe.**

I am using `external-dns` to expose services in my k8s cluster to Pi-holes. Vault is one of those services. I am using the following YAML values for the Helm chart:

```yaml
server:
  ingress:
    enabled: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "vault.k8s-cluster.local"
```

This annotation is getting applied to both the `vault-internal` and `vault` services. It's causing issues with `external-dns` and is ending up setting the DNS to `10.*` addresses, rather than the `192.168.*` address I would be expecting.

**Describe the solution you'd like**

Feature request: please split the annotations which get applied to these two services, that way I can specify an annotation *just* for the `vault` service. Possible YAML values structure could be:

```yaml
server:
  service:
    internal:
      annotations: {}
    external:
      annotations: {}
```

**Describe alternatives you've considered**

I've been unable to determine any alternative action I can take.
