### ISSUE TITLE
Add support for setting appProtocol in Vault Service definitions to improve Gateway API HTTPS backend support

### ISSUE THREAD

**Issue by rgarcia89** [hashicorp/vault-helm#1108]
### Problem

Currently, the Vault Helm chart (`hashicorp/vault-helm`) does not set the `appProtocol` field in the Kubernetes `Service` definition for Vault.

In modern Kubernetes Gateway API setups - particularly when using cloud provider managed Gateways such as Google Kubernetes Engine (GKE) Gateway Controller - setting the `appProtocol` is required to enable proper HTTPS communication and health checks between the Gateway and backend services.

Without `appProtocol: https`, Gateways attempt to perform backend traffic over plain HTTP, leading to failed connections when the Vault service is only available via HTTPS.

Relevant GKE documentation:  
- [Secure a Gateway with TLS - GKE Docs](https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#load-balancer-tls)

### Requested Feature

Enhance the Helm chart to allow setting `appProtocol` for the Service ports via `values.yaml`, e.g.,:

```yaml
server:
  service:
    ports:
      - name: https
        port: 8200
        targetPort: 8200
        protocol: TCP
        appProtocol: https
```
