### ISSUE TITLE
How can I input a multi-line annotation with vault?

### ISSUE THREAD

**Issue by ado120** [hashicorp/vault-helm#117]
```
  # Extra annotations to attach to the ui service
  # This should be a multi-line string mapping directly to the a map of
  # the annotations to apply to the ui service
  annotations: {}

```
This is how my values looks like:
```
ui:
  enabled: true
  serviceType: LoadBalancer
  externalPort: 8200
  annotations: |
    external-dns.alpha.kubernetes.io/hostname: dns_name
    service.beta.kubernetes.io/aws-load-balancer-security-groups: sg_group


```

Getting a Error: YAML parse error on vault/templates/ui-service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field .annotations of type map[string]string

Just to note that I do the same exact thing with the consul-helm chart and it works fine
