### ISSUE TITLE
Add Nodeport type and port in the Service server configuration

### ISSUE THREAD

**Issue by aalcaraz97** [hashicorp/vault-helm#127]
I'm trying to deploy a KIND cluster with the Vault Helm Chart and the Consul Helm Chart in it, and another KIND cluster with my application, which also contains vault-agent and consul-template as initContainers.

I want my vault-agent and consul-template in one cluster to retrieve the secret from the Vault server in another. To do that, I need to expose the 8200 Vault port in the KIND cluster where my Vault and Consul servers are with a NodePort, to allow connection between the two KIND clusters.

I have inspected the _values.yaml_ file in the Vault Helm Chart, and I have seen that the Nodeport option is only available in the _ui_ configuration, and not into the _server.service_ configuration. 

Is there a way this option can be added in the _values.yaml_ to select the NodePort type in the server-service.yaml and also the nodePort port value?

This is my configuration:

- Helm v3.0.0
- kind v0.5.1
- docker v19.03.2
- kubectl v1.15.3

**Comment by jasonodonnell** [comment]
Hi @aalcaraz97!

So there is an [undocumented configurable for changing the service type](https://github.com/hashicorp/vault-helm/blob/master/templates/server-service.yaml#L22-L24), so you can change this to NodePort if you would like.  Unfortunately there isn't a configurable for setting the NodePort, so you would get a random node port which is kind of annoying.

We can add a configurable specifically for node port in the Vault service.

As a workaround, you can create your own NodePort service manually:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  namespace: <YOUR NAMESPACE>
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 30000
    - name: internal
      port: 8201
      targetPort: 8201
      nodePort: 30001
  selector:
    app.kubernetes.io/name: <NAME OF YOUR VAULT DEPLOYMENT>
    component: server
```
