### ISSUE TITLE
Injector errors

### ISSUE THREAD

**Issue by bweston92** [hashicorp/vault-helm#156]
Just upgraded Chart to v0.3 and tried to take advantage of the injector.

However I get the following errors:

```
Error loading configuration from /tmp/config.json: error parsing 'template': error converting config
```

Annotations:

```
vault.hashicorp.com/agent-inject: "true"
vault.hashicorp.com/role: "public-apis"
```

Was wanting a way of getting a Vault token and for it to be renewed whilst the pod was alive.

**Comment by jasonodonnell** [comment]
Hi @bweston92, you have to define at least one secret annotation.  I'll add validation code to `vault-k8s` to ensure at least one exists.

```yaml
vault.hashicorp.com/agent-inject-secret-foo: "secret/mysecret"
```

**Comment by bweston92** [comment]
@jasonodonnell that makes sense.

I have ended up with

```yaml
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
        vault.hashicorp.com/agent-inject-template-token: |
          {{- with secret "auth/token/lookup-self" -}}
          {{.Data.id}}
          {{- end }}
        vault.hashicorp.com/role: "public-apis-role"
```

Seems a lot to just get the token though.
