### ISSUE TITLE
Unable to deploy injector only

### ISSUE THREAD

**Issue by herrbpl** [hashicorp/vault-helm#173]
Attempt to deploy following configuration:

```
global:
    enabled: false
  injector:
    # True if you want to enable vault agent injection.
    enabled: true
```
results following error from helm:
**Error: release vault-injector failed: no objects visited**

Expected result: 
- Injector Agent installed

Actual result:
- Deployment fails

Helm template version 0.3.2
Target Environment: Rancher v2.3.2
