### ISSUE TITLE
Is it OK to use liveness probe setting?

### ISSUE THREAD

**Issue by b4b4r07** [hashicorp/vault-helm#180]
I have a question related to use HashiCorp Vault more safely on Kubernetes with Helm.

Your helm chart has liveness probe setting: https://github.com/hashicorp/vault-helm/blob/551f292b6f9a0a51f596c7180e50045298c63382/templates/server-statefulset.yaml#L110-L118

But this means the sealed pods will be deleted for restarting when the pods get sealed. Is it OK as Vault unseal policy? Should we unseal sealed pods manually, or not?

**Comment by jasonodonnell** [comment]
You can customize what the health endpoint URL considers healthy.  For example:

```
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    initialDelaySeconds: 5
```

Hope that helps.
