### ISSUE TITLE
DNS: default backend - 404

### ISSUE THREAD

**Issue by fbongiovanni29** [hashicorp/vault-helm#191]
I can access vault from the IP I set it up with but when I point an A record at it I get `default backend - 404`. Feels like an ingress issue, this is my setup
```
  ingress:
    enabled: true
    labels: {}
      # traffic: external
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: vault.xxx.xxx.org
        paths: ["/"]
```
```
kubectl get ingress -n vault
NAME    HOSTS                            ADDRESS   PORTS   AGE
vault   vault.xxx.xxx.org             80      37s
```
