### ISSUE TITLE
how can I create AWS ALB with ingress values?

### ISSUE THREAD

**Issue by q0115643** [hashicorp/vault-helm#204]
In the values.yaml, I implemented ingress as below
```
...
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/healthcheck-path: /v1/sys/health?standbyok=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: {{Reducted}}
      alb.ingress.kubernetes.io/certificate-arn: {{Reducted}}
      alb.ingress.kubernetes.io/tags: Type=ingress
      external-dns.alpha.kubernetes.io/hostname: {{Reducted}}
      external-dns.alpha.kubernetes.io/ttl: "60"
    hosts:
      - host: {{Reducted}}
        paths: 
        - /*
...
```
but I cannot see my alb created, nor a route53 record by external-dns. Is this a bug?
