### ISSUE TITLE
Can't set namespaceSelector with values.yaml example

### ISSUE THREAD

**Issue by Sphinxgaia** [hashicorp/vault-helm#205]
Hello,

an issue occur when setup namespaceSelector (in injector section) with example

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[0].namespaceSelector): invalid type for io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector: got "string", expected "map"
```

Bad examples in `values.yaml`
```yaml
#values.yaml

  namespaceSelector: |
    matchLabels:
      sidecar-injector: enabled
  #  namespaceSelector: {}
```

I solve using like this :
```yaml
#values.yaml

  # namespaceSelector: |
  #    matchLabels:
  #      sidecar-injector: enabled
  namespaceSelector: 
    matchExpressions: 
      - key: vault-sidecar-injector
        operator: In
        values: ["enabled","true"]
```

best regards

**Comment by grozan** [comment]
got the same problem. That fails

```
  namespaceSelector: |
    matchLabels:
      vault-sidecar-injector: enabled
```

it should not be a multiline string. The following works

```
  namespaceSelector:
    matchLabels:
      vault-sidecar-injector: enabled
```

**Comment by Sphinxgaia** [comment]
Fixed on master branch, 
if you follow the Kubernetes doc, you should use :
```yaml
namespaceSelector: 
    matchExpressions: 
      - key: vault-sidecar-injector
        operator: In
        values: ["enabled","true"]
```

closed

/fix by #227
