### ISSUE TITLE
AWS ALB's health-check fails with "Request timed out"

### ISSUE THREAD

**Issue by q0115643** [hashicorp/vault-helm#209]
I used aws-alb-ingress-controller and external-dns to create my ALB for vault server on k8s.
I created ALB in a public subnet, and vault server in private subnets.

```
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/healthcheck-path: /v1/sys/health?standbyok=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/subnets: REDUCTED
      alb.ingress.kubernetes.io/security-groups: REDUCTED
      alb.ingress.kubernetes.io/certificate-arn: REDUCTED
      alb.ingress.kubernetes.io/tags: REDUCTED
      external-dns.alpha.kubernetes.io/hostname: my-domain.com
      external-dns.alpha.kubernetes.io/ttl: "60"
    hosts:
      - host: my-domain.com
        paths: 
        - /*
```
when I checked vault ui by kubect port-forward, it worked well on localhost.
ALB and domain was properly created.
but https://my-domain.com shows 504 error.
health check fails on target group.
Problem was not resolved on adding all ports to security groups or changing alb target-type to ip.
