### ISSUE TITLE
Vault init/sidecar containers not spinning up with externalVaultAddr

### ISSUE THREAD

**Issue by fbongiovanni29** [hashicorp/vault-helm#214]
```
injector:
  # True if you want to enable vault agent injection.
  enabled: true

  # External vault server address for the injector to use. Setting this will
  # disable deployment of a vault server along with the injector.
  externalVaultAddr: "https://vault.myorg.com"

  # image sets the repo and tag of the vault-k8s image to use for the injector.
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.2.0"
    pullPolicy: IfNotPresent

  # agentImage sets the repo and tag of the Vault image to use for the Vault Agent
  # containers.  This should be set to the official Vault image.  Vault 1.3.1+ is
  # required.
  agentImage:
    repository: "vault"
    tag: "1.3.2"

  # namespaceSelector is the selector for restricting the webhook to only
  # specific namespaces. This should be set to a multiline string.
  # See https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector
  # for more details.
  # Example:
  # namespaceSelector: |
  #    matchLabels:
  #      sidecar-injector: enabled
  namespaceSelector: {}

  certs:
    # secretName is the name of the secret that has the TLS certificate and
    # private key to serve the injector webhook. If this is null, then the
    # injector will default to its automatic management mode that will assign
    # a service account to the injector to generate its own certificates.
    secretName: null

    # caBundle is a base64-encoded PEM-encoded certificate bundle for the
    # CA that signed the TLS certificate that the webhook serves. This must
    # be set if secretName is non-null.
    caBundle: ""

    # certName and keyName are the names of the files within the secret for
    # the TLS cert and private key, respectively. These have reasonable
    # defaults but can be customized if necessary.
    certName: tls.crt
    keyName: tls.key

  resources: {}
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 250m
  #   limits:
  #     memory: 256Mi
  #     cpu: 250m
```
Agent injector pod appears fine:
```
kubectl logs vault-agent-injector-646b586bc9-px27w -n vault
Listening on ":8080"...
2020-02-24T16:33:30.544Z [INFO]  handler: Starting handler..
Updated certificate bundle received. Updating certs...
```
Given example deployment ([adapted from here](https://learn.hashicorp.com/vault/getting-started-k8s/sidecar))
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  labels:
    app: vault-agent-injector-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-injector-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
      labels:
        app: vault-agent-injector-demo
    spec:
      serviceAccountName: internal-app
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1
```
No init or sidecar container comes up:
```
kubectl get pods -w
NAME                        READY   STATUS    RESTARTS   AGE
orgchart-77664bfc56-45npg   0/1     Pending   0          0s
orgchart-77664bfc56-45npg   0/1     Pending   0          0s
orgchart-77664bfc56-45npg   0/1     ContainerCreating   0          0s
orgchart-77664bfc56-45npg   1/1     Running             0          1s
```
This same deployment works in my setup where I have the vault server & ui (no externalVaultAddr) running via the helm chart install

**Comment by fbongiovanni29** [comment]
I'm also curious how to [configure kubernetes authentication](https://learn.hashicorp.com/vault/getting-started-k8s/sidecar#configure-kubernetes-authentication) without a vault server pod

**Comment by tvoran** [comment]
Hi @fbongiovanni29, I haven't been able to reproduce your issue yet; the only thing I can think of is the mutating webhook config isn't getting deployed correctly. i.e. you should see this:

```shell
➜ kubectl get mutatingwebhookconfigurations        
NAME                       CREATED AT
vault-agent-injector-cfg   2020-02-26T21:29:25Z
```

And the manifest should be present in the helm deployment, something like this:

```shell
➜ helm get manifest vault
...
---
# Source: vault/templates/injector-mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: vault.hashicorp.com
    clientConfig:
      service:
        name: vault-agent-injector-svc
        namespace: default
        path: "/mutate"
      caBundle: 
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
...
```

For your second question, the external vault will need connectivity to the kubernetes API endpoint, then you can setup auth something like this, assuming a k8s service account named `vault-auth` exists, and your kubectl config is configured for the k8s cluster:

```shell
TOKEN_REVIEW_JWT=$(kubectl get secret vault-auth -n vault -o go-template='{{ .data.token }}' | base64 --decode)
KUBE_CA_CERT=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 --decode)
KUBE_HOST=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.server}')

vault auth enable kubernetes

vault write auth/kubernetes/config \
  token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
  kubernetes_host="$KUBE_HOST" \
  kubernetes_ca_cert="$KUBE_CA_CERT"
```

**Comment by fbongiovanni29** [comment]
Thanks for looking, I don't see anything wrong with the mutating webhook config
```
> kubectl get mutatingwebhookconfigurations
NAME                                                 CREATED AT
pod-ready.config.common-webhooks.networking.gke.io   2019-10-10T01:04:04Z
vault-agent-injector-cfg                             2020-02-27T01:36:14Z
```
Or the helm deployment manifest:
```
helm get manifest vault -n vault
...
---
# Source: vault/templates/injector-mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: vault.hashicorp.com
    clientConfig:
      service:
        name: vault-agent-injector-svc
        namespace: vault
        path: "/mutate"
      caBundle:
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
```
I'll keep digging into this, maybe I'm missing something obvious
