### ISSUE TITLE
[BUG]auto unseal VAULT_TOKEN env can't get from secret.

### ISSUE THREAD

**Issue by klw0539** [hashicorp/vault-helm#242]
Dear,

I use [Transit Secrets Engine](https://learn.hashicorp.com/vault/operations/autounseal-transit) method for auto unseal in my HA mode vault cluster.  As the guide we need to `export VAULT_TOEKN` to environment. So I want to store the auto unseal token as a secret and export it to environment from secret, as below:
```
apiVersion: v1
kind: Secret
metadata:
  name: consul-secret
  namespace: levy-test
type: Opaque
data:
  autounsela-token: cy5Kd0Y2NUZVUUs5cDZrYUlaQ2Z2TVpoQmIK
```
set the extraSecretEnvironmentVars in `values.yaml` like below:
```
extraSecretEnvironmentVars:
    - envName: VAULT_TOKEN
      secretName: consul-secret
      secretKey: autounsela-token
```
generated statefulset env like this:
```
           env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8200"
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-secret
                  key: autounsela-token
```
However, when the pods started, container become to **error**:
```
wse-vault-prod-0            0/1     Error              4          95s
```
and according to the logs:
```
$~: k logs -f wse-vault-prod-0
Error parsing Seal configuration: configured Vault token contains non-printable characters and cannot be used
```
If I set the env `VAULT_TOKEN` real value in the statefulset env like below:
```
env:
...
           - name: VAULT_TOKEN
              value: "s.JwF65FUQK9p6kaIZCfvMZhBb"
```
The pod is running fine.

I'm sure the `VAULT TOKEN` in the secret is correct. because I have verified it by set it to `VAULT TOEKN_1` and print it out in container. Like below:
```
           env:
            - name: VAULT_TOKEN
              value: "s.JwF65FUQK9p6kaIZCfvMZhBb"
            - name: VAULT_TOKEN_1
              valueFrom:
                secretKeyRef:
                  name: consul-secret
                  key: autounsela-token
```
the printout is:
```
k exec -it wse-vault-prod-0 sh
/ $ echo $VAULT_TOKEN
s.JwF65FUQK9p6kaIZCfvMZhBb
/ $ echo $VAULT_TOKEN_1
s.JwF65FUQK9p6kaIZCfvMZhBb
```
I tried several times, the results are same.

I think it may be a bug, so report it, could you please check this issue and confirm if I did correctly.

Thanks.
