### ISSUE TITLE
SSL mode activation for PostgreSQL Backend Storage fails

### ISSUE THREAD

**Issue by woowil** [hashicorp/vault-helm#246]
SSL mode activation for PostgreSQL Backend Storage fails since the Vault container creation tries to use the CA from /vault/userconfig/psql-tls/BaltimoreCyberTrustRoot.crt.pem before the volume has been mounted

```bash
$ kubectl get secret psql-tls
NAME       TYPE     DATA   AGE
psql-tls   Opaque   1      7h8m
```
vaules.yaml
```yaml
server 
  extraVolumes:
    - type: secret
      name: vault-tls # Matches kubectl get secret <name> --namespace vault
      #load: false
    - type: secret
      name: psql-tls # Matches kubectl get secret <name> --namespace vault
      #load: false
 ha:
    config: |
      connection_url = "host=********.postgres.database.azure.com port=5432 dbname=vault user=********@******** password=******** connect_timeout=30 sslmode=verify-full sslrootcert=/vault/userconfig/psql-tls/BaltimoreCyberTrustRoot.crt.pem"
```

```bash     
$ kubectl logs vault-0
Error initializing storage of type postgresql: failed to check for native upsert: open /vault/userconfig/psql-tls/BaltimoreCyberTrustRoot.crt.pem: no such file or directory
```
