### ISSUE TITLE
add podAnnotations: 

### ISSUE THREAD

**Issue by jmturwy** [hashicorp/vault-helm#262]
I'd love to use my kiam and AWS roles to auto-unseal with the chart. this would allow my pod to use my aws role instead of using IAM user client and secrets

Example:
podAnnotations:
  iam.amazonaws.com/role: k8s_vault

**Comment by silverbp** [comment]
you can add the annotation to the service account via this..

```
  serviceAccount:
    annotations:
      |
      "eks.amazonaws.com/role-arn": "${aws_role_arn}"
```

but it doesn't work, I don't think it has to do with helm, I don't think the vault docker image is reading the environment variables and the token that are getting injected, cause when I do the above, I get the proper environment variables set, but vault errors out (no access) because it's using the node arn role when it should be using the arn that's assigned above.
