### ISSUE TITLE
Unable to use the helm chart on openshift

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [hashicorp/vault-helm#275]
I am trying to deploy this on openshift but getting the following errors:

```
failed error: pods "vault-0" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "IPC_LOCK": capability may not be added fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000640000, 1000649999] capabilities.add: Invalid value: "IPC_LOCK": capability may not be added]

injector-58b55d8df4         Error creating: pods "vault-agent-injector-58b55d8df4-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 100: must be in the ranges: [1000640000, 1000649999]]

```

Any workaround for this ? I tried setting `SecurityContextConstraints` as well but it didn't help

**Comment by pcman312** [comment]
Thanks for opening this issue! What did you set `SecurityContextConstraints` to? We've been able to use the following config successfully:
```yaml
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: vault-auth-scc
users:
- system:serviceaccount:vault-demo:app1
requiredDropCapabilities:
- MKNOD
- SYS_CHROOT
runAsUser:
  type: MustRunAs
  uid: 100
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 2000
seLinuxContext:
  type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```

**Comment by ahmedwaleedmalik** [comment]
Thanks @pcman312 this worked for me. Closing this issue

**Comment by michaelryanmcneill** [comment]
This did not work for me, but I modified it to work for me (on OpenShift 4.3 using v0.5.0 of the chart):

```
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: vault-auth-scc
users:
- system:serviceaccount:vault:vault
- system:serviceaccount:vault:vault-agent-injector
requiredDropCapabilities:
- MKNOD
- SYS_CHROOT
runAsUser:
  type: MustRunAs
  uid: 100
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 2000
allowedCapabilities:
- IPC_LOCK
- SYS_RESOURCE
seLinuxContext:
  type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```
