### ISSUE TITLE
Templating issues with ingress

### ISSUE THREAD

**Issue by nitro2003** [hashicorp/vault-helm#278]
Steps to replicate:

Defined ingress configuration based on [documentation](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#hosts).

Tested with the following configuration:

`  ingress:
    enabled: true
    labels: {}
      # traffic: external
    annotations: |-
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      
    hosts:
      - host: vault.dev.coinspectapp.com
        paths:
          - backend:
            serviceName: dev-vault
            servicePort: 8200`

Also the following:
`paths:
  - backend:
    serviceName:
    servicePort: `

`paths: []`

Working:
`        paths:
          - "" `

Expected: 
- Should work as per documentation

Actual:
- errors were encountered.

Error: 
Ingress.extensions "dev-vault" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "map[backend:<nil> serviceName:dev-vault servicePort:8200]": must be an absolute path

Manifest:
![image](https://user-images.githubusercontent.com/10734493/80334731-a7c53000-8884-11ea-9112-e092380a2ac9.png)

Vault is installed using helm with the following tar file:
- https://github.com/hashicorp/vault-helm/archive/v0.5.0.tar.gz

I am not an expert, this could just be all my fault.
I just tried to follow the documentation.

Thanks!

**Comment by nohaj** [comment]
My configuration : 

````
ingress:
    enabled: true
    hosts:
      - host: vault.mydomain.com
    tls:
      - host: vault.mydomain.com
        secretName: vault
````

Was not working with the 0.5.0 version of the chart but it works with the master branch of the ingress template.

Thanks to jaredallard (https://github.com/hashicorp/vault-helm/pull/224/commits/7568cb12396629febc88f236a93fdb44c22e7ab8)

**Comment by nohaj** [comment]
My configuration : 

````
  ingress:
    enabled: true
    hosts:
      - host: vault.mydomain.com
    tls:
       - hosts:
         - vault.mydomain.com
         secretName: vault
````

Was not working with the 0.5.0 version of the chart but it works with the master branch of the ingress template.

Thanks to jaredallard (https://github.com/hashicorp/vault-helm/pull/224/commits/7568cb12396629febc88f236a93fdb44c22e7ab8)

**Comment by tvoran** [comment]
Hi @nitro2003, indeed it looks like the documentation for the ingress values is a little out of date, sorry about that. The `paths` list in `Values.server.ingress.hosts[]` should just be a list of path strings, since the chart template already defines the `backend` stanza: https://github.com/hashicorp/vault-helm/blob/2a37c571d77a528783a9d16a77becc91e21ccab6/templates/server-ingress.yaml#L35-L41

So I think in your case, you'd want something like this set in the values:
```yaml
    hosts:
      - host: vault.dev.coinspectapp.com
        paths:
          - /
```

(In the upcoming release the `paths` list defaults to ['/'], so that's why the master branch behaves a little differently. We'll get the docs fixed too.)
