### ISSUE TITLE
Resources & Annotations: Map or String?

### ISSUE THREAD

**Issue by issacg** [hashicorp/vault-helm#292]
According to the docs [resources](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#resources) and [annotations](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#annotations) should be strings.

According to the defaults in values.yaml it seems that both should be maps.  Indeed trying to follow the docs gives me the following output:
```
coalesce.go:196: warning: cannot overwrite table with non table for resources (map[])
coalesce.go:196: warning: cannot overwrite table with non table for annotations (map[])
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].resources): invalid type for io.k8s.api.core.v1.ResourceRequirements: got "string", expected "map"
```

Are the docs wrong (outdated)? Or am I possibly doing something wrong?

I have an overrides file with snippets like these:
```yaml
injector:
  resources: |
    requests:
      memory: 64Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 250m

server:
  ingress:
    annotations: |
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: vault
```

**Comment by pcman312** [comment]
Thanks for the issue! It looks like our documentation is incorrect. `resources` is a map type and `annotations` can be either a map type or a YAML-formatted multi-line string.

**Comment by oliviermichaelis** [comment]
I can confirm that removing the `|` works, but I still get the following warning:
```
coalesce.go:195: warning: destination for resources is a table. Ignoring non-table value <nil>
```
How do we get rid of the warning?


My overriding file looks like this:
```
server:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m
```
and it templates out to this with `helm template`:
```
containers:
  - name: vault
    resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
```
