### ISSUE TITLE
Sidecar TLS Issue With Self-Managed TLS Certificates

### ISSUE THREAD

**Issue by nafarlee** [hashicorp/vault-helm#293]
```yaml
# relevant versions
helm-version: 3.2.0
kubectl-version: 1.15.5
cluster-type: kubernetes
cluster-version: 1.5.11-gke.9
platform: gke
```
```yaml
# values.yaml
---
global:
  tlsDisable: false

injector:
  image:
    tag: "0.3.0"
  agentImage:
    tag: "1.4.0"

server:
  image:
    tag: "1.4.0"
  extraEnvironmentVars:
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/credentials/gcp.json
  extraVolumes:
    - type: secret
      name: credentials
      path: /vault/userconfig
    - type: secret
      name: certificate-tls
      path: /vault/userconfig
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  dataStorage:
    enabled: false
  auditStorage:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true

      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/certificate-tls/tls.crt"
        tls_key_file = "/vault/userconfig/certificate-tls/tls.key"
      }

      storage "gcs" {
        bucket = "REDACTED"
        ha_enabled = "true"
      }

      service_registration "kubernetes" {}

      seal "gcpckms" {
        credentials = "/vault/userconfig/credentials/gcp.json"
        project = "REDACTED"
        region = "global"
        key_ring = "vault"
        crypto_key = "unseal"
      }

ui:
  enabled: true
  serviceType: "LoadBalancer"
  externalPort: 443
  annotations: |
    external-dns.alpha.kubernetes.io/hostname: REDACTED
```

Vault is successfully configured, initialized, and exposed *outside* of the cluster over TLS using a self-managed certificate. To be clear, the certificates are within a Kubernetes Secret, and are mounted as a volume within the main Vault pods, which are then referenced within Vault's `listener "tcp"` configuration.

However, now in attempting to enable vault-agent sidecar connections from *inside* the cluster, I am getting TLS issues.

Assume I have the following Deployment, and the referenced namespace, service account, and role already exist and are configured appropriately:
```yaml
# deployment.yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: vault-sidecar-demo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: vault-sidecar-demo
        vault.hashicorp.com/agent-inject-secret-helloworld: secret/hello
      labels:
        app: nginx
    spec:
      serviceAccountName: vault-sidecar
      containers:
        - name: nginx
          image: nginx:alpine
```

Applying this Deployment results in a pod hung in the `Init:0/1` status. Looking at the logs of the `vault-agent-init` container in said pod, we can see the following message repeating ad infinitum (Do not mind the `REDACTED`; I am omitting the real common name):

```
2020-05-06T21:19:27.871Z [INFO]  auth.handler: authenticating
2020-05-06T21:19:27.877Z [ERROR] auth.handler: error authenticating: error="Put https://vault.vault.svc:8200/v1/auth/kubernetes/login: x509: certificate is valid for REDACTED, not vault.vault.svc" backoff=1.523971289
2020-05-06T21:19:29.401Z [INFO]  auth.handler: authenticating
2020-05-06T21:19:29.410Z [ERROR] auth.handler: error authenticating: error="Put https://vault.vault.svc:8200/v1/auth/kubernetes/login: x509: certificate is valid for REDACTED, not vault.vault.svc" backoff=2.92481153
```

If I add the following annotation to the Deployment, the sidecar starts up successfully, and the filesystem is populated by the aforementioned secret:

```yaml
# deployment annotation
vault.hashicorp.com/tls-skip-verify: true
```

This is a decent compromise, but it does mean that the sidecar has no way of validating Vault, and this annotation must be added to every usage of the sidecar.

I thought that `externalVaultAddr` might be a solution, as I can just specify my public, TLS-enabled address of Vault, and though it would cause requests to leave the cluster, they would be over a trusted HTTPS conection, but as you know, setting this field prevents this chart from creating Vault pods.

Am I configuring TLS in a way that is not supported by this chart, or am I missing some additional configuration to make the sidecars connect using my current TLS configuration?
