### ISSUE TITLE
Helm cannot install the chart if the global settings is disabled

### ISSUE THREAD

**Issue by aliabbasjaffri** [hashicorp/vault-helm#306]
If the global settings are disabled but the individual settings are enabled, the helm doesn't seem to install the chart, with the `error: no objects visited`

**Comment by krzysztof-miemiec** [comment]
I think it's related to this Helm issue: https://github.com/helm/helm/issues/4670

TL;DR: Helm assumes it's invalid to deploy no resources. Additionally, Helm assumes it's invalid to deploy only Secrets/ConfigMaps/Jobs.

My issue is that I can't deploy only an injector with such `vaules.yaml`:
```yaml
global:
  enabled: false
injector:
  authPath: kubernetes/cluster-beta
  enabled: true
  externalVaultAddr: https://vault.example.com
  logFormat: json
  priorityClassName: required
  resources:
    limits:
      cpu: 20m
      memory: 100Mi
    requests:
      cpu: 5m
      memory: 50Mi
  revokeOnShutdown: true

```

One of proposed workarounds is to always deploy a dummy `Deployment` with replicas count set to `0`.

**Comment by bitfactory-henno-schooljan** [comment]
The documentation says you can disable the global setting and enable components selectively:

https://www.vaultproject.io/docs/platform/k8s/helm/configuration#enabled

However, this is not true. It will never work, as the chart checks for both values to be `true`:

https://github.com/hashicorp/vault-helm/blob/0c28645748ef4cb6b4b24dca4e3a48faadded5ad/templates/injector-deployment.yaml#L1

**Comment by krzysztof-miemiec** [comment]
@bitfactory-henno-schooljan that's true. When I created a chart dummy deployment, only the deployment was created, so it was not a Helm bug there. I ended up reading the source of this Helm chart and came up with this:
```yaml
injector:
  enabled: true
  externalVaultAddr: https://vault.example.com # This is the important part here
  authPath: kubernetes/cluster-beta

  logFormat: json
  revokeOnShutdown: true
  namespaceSelector: null

  resources:
    requests:
      cpu: 5m
      memory: 50Mi
    limits:
      cpu: 20m
      memory: 100Mi
```

`injector.externalVaultAddr` is enough for chart to disable everything besides injector and connect to Vault at specified address. If you play with other flags (like `server.enable=false`), it doesn't work correctly.
