### ISSUE TITLE
Vault injector not working in a KIND cluster

### ISSUE THREAD

**Issue by aalcaraz97** [hashicorp/vault-helm#312]
I have a Kubernetes cluster created using KIND. I also have a Vault server using Consul as backend, deployed outside the K8S cluster. I was using Kubernetes Deployments with Vault Agent + Consul Template to retrieve the secrets and pass them to the application container. Now I want to use Vault K8S injector.

My setup with K8S injector is currently not working, and it worked before when using Vault Agent + Consul Template. This is my current setup (I'm deploying a nginx container that retrieves a secret from Vault):

- KIND version: v0.8.1
- Kubectl version: v1.18.2
- Docker version: v19.03.8

KIND cluster-config.yaml:

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        listenAddress: "0.0.0.0"
```
nginx-deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    run: nginx
    version: vault-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
      version: vault-injector
  template:
    metadata:
      labels:
        app: nginx
        run: nginx
        version: vault-injector
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "nginx"
        vault.hashicorp.com/auth-path: "kubernetes-nginx-vault-injector"
        vault.hashicorp.com/agent-inject-secret-demo: "secret/nginx/demo"
        vault.hashicorp.com/secret-volume-path-demo: "/root/secret"
        vault.hashicorp.com/agent-inject-template-demo: |
          {{`{{- with secret "secret/nginx/demo" -}}
          {{ .Data.secretvalue }}
          {{ end }}`}}
    spec:
      serviceAccountName: vault-auth-nginx
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 80
```
nginx-service.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 80
    name: http
  selector:
    run: nginx
```
nginx-vault-service-account.yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-nginx
  namespace: nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-nginx
  namespace: nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth-nginx
    namespace: nginx
    
```
nginx-vault-policy.hcl:
```
# If working with K/V v1
path "secret/nginx/*" {
    capabilities = ["read", "list"]
}
```
bash script to enter vault secrets, configure vault with k8s auth method, and deploy all the k8s files:
```
# At this point, Vault is already initialized and unsealed
# $VAULT_ADDR env var is already exported and contains the address of the Vault server
# Put secret in Vault server
vault secrets enable -path=secret kv
vault kv put secret/nginx/demo secretname='nginx' secretvalue='demodemo'

# Configuring nginx cluster to connect with Vault
kubectl create namespace nginx
kubectl apply -f ./nginx-vault-service-account.yaml --namespace=nginx

export VAULT_SA_NAME=$(kubectl get sa -n nginx vault-auth-nginx -o jsonpath="{.secrets[*]['name']}")
export SA_JWT_TOKEN=$(kubectl get secret -n nginx $VAULT_SA_NAME -o jsonpath="{.data.token}" | base64 --decode; echo)
export SA_CA_CRT=$(kubectl get secret -n nginx $VAULT_SA_NAME -o jsonpath="{.data['ca\.crt']}" | base64 --decode)
export K8S_HOST=https://$(kubectl get nodes -o wide | grep 'nginx-control-plane' |  awk '{print $6}'):6443

vault login $VAULT_TOKEN # contains the Vault initial root token
vault auth enable -path=/kubernetes-nginx-vault-injector kubernetes
vault policy write nginx-kv-policy ./nginx-vault-policy.hcl
vault write auth/kubernetes-nginx-vault-injector/config token_reviewer_jwt="$SA_JWT_TOKEN" kubernetes_host="$K8S_HOST" kubernetes_ca_cert="$SA_CA_CRT"
vault write auth/kubernetes-nginx-vault-injector/role/nginx bound_service_account_names=vault-auth-nginx bound_service_account_namespaces=nginx policies=nginx-kv-policy ttl=10m

# Add Vault Helm repository in the cluster and install Vault Helm chart
helm repo add --namespace nginx hashicorp https://helm.releases.hashicorp.com
helm install --namespace nginx vault hashicorp/vault \
--set="injector.enabled=true" \
--set="injector.externalVaultAddr=$VAULT_ADDR" \
--set="injector.authPath=auth/kubernetes-nginx-vault-injector" \
--set extraEnvironmentVars[0].name=AGENT_INJECT_VAULT_ADDR,extraEnvironmentVars[0].value=$VAULT_ADDR 

# Deploy K8S nginx deployment and service
kubectl apply -f ./nginx-deployment.yaml --namespace=nginx
kubectl apply -f ./nginx-service.yaml --namespace=nginx
```

These are the logs of the vault injector pod:
```
kubectl logs -n nginx vault-agent-injector-776c979c4c-wnv2s
Listening on ":8080"...
2020-05-21T11:23:41.363Z [INFO]  handler: Starting handler..
Updated certificate bundle received. Updating certs...

```
Then I entered the nginx pod, to see if the secret was present in the path that I specified (/root/secret), with no results:
```
kubectl exec -it -n nginx nginx-55bf89f68f-4k2d6 -- ls -lah /root
total 8.0K
drwx------. 2 root root  37 May 14 14:50 .
drwxr-xr-x. 1 root root  39 May 21 11:23 ..
-rw-r--r--. 1 root root 570 Jan 31  2010 .bashrc
-rw-r--r--. 1 root root 148 Aug 17  2015 .profile
```

I also checked if there was a /vault/secrets folder inside the pod, but it was not created. Do you have a clue of what I am doing wrong? Thanks!
