### ISSUE TITLE
Sidecar injection does not trigger on deployments with annotations

### ISSUE THREAD

**Issue by rchenzheng** [hashicorp/vault-helm#335]
### VERSIONS
- GKE v1.15.11
- HELM v2.13.1
- chart 0.6.0
- External Vault server: 1.4.2

### CONFIG
```
injector:
  logLevel: debug
  authPath: "auth/kubernetes-my-cluster"
  externalVaultAddr: "https://myvault.com"

fullnameOverride: vault
```

### ISSUE
The deployment with the following annotations don't get injected

```
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: hello-world-go
  labels: 
      name: "hello-world"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-hello-world: "secret/hello-world"
    vault.hashicorp.com/role: "hello-world"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hello-world-go"
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world-go
    spec:
      serviceAccountName: hello-secrets 
      containers:
        - image: hello-world-go
          imagePullPolicy: Always 
          name: hello-world-go
          command: ["/server"]
          ports:
            - containerPort: 8080       
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
          securityContext:
            privileged: true

```

### TROUBLESHOOTING STEPS PERFORMED

- Confirm ServiceAccount for authentication have been created

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault
secrets:
- name: vault-auth-token-z7x96
```

- Auth endpoints have also been configured

- Secrets have been created and confirmed accessible

- Error logs available from the pod:

```
│ 2020-06-22T20:55:03.363Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s                                                                                                          │
│ 2020-06-22T20:55:03.363Z [DEBUG] handler: checking if should inject agent..
```

- Based on other issues closed, I've also whitelisted the master's CIDR to be allowed to access the network via 8080 
https://github.com/hashicorp/vault-helm/issues/214
