### ISSUE TITLE
Four securityContext parameters are not generated (runAsNonRoot, runAsGroup, runAsUser, fsGroup)

### ISSUE THREAD

**Issue by manderson-it** [hashicorp/vault-helm#343]
Helm Chart: 0.6.0
Helm Command (works as expected): `helm template vault vault-0.6.0.tgz > vault-all-new.yaml`
This results in the StatefulSet with the following:
```
       securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 100
        fsGroup: 1000
```

When run with this command all four parameters are omitted from the StatefulSet (runAsNonRoot, runAsGroup, runAsUser, fsGroup). 
Helm command (does not generate the securityContext parameters):
```
    helm template vault hashicorp/vault --namespace "xyz"
    --values "values-minimal.yaml"
    --set='server.image.repository=hashicorp/vault-enterprise'
    --set='server.image.tag=1.4.2_ent'
    --set='server.ha.enabled=true'
    --set='server.ha.raft.enabled=true'
    --set='server.route.enabled=true'
    --set='server.extraEnvironmentVars.VAULT_CACERT=/vault/userconfig/vault-tls/vault.ca'
    --set='server.tls.secretName=vault-tls'
    --set='global.tlsDisable=false'
    --set='global.openshift=true'
    > "/home/user/vault-all.yaml"
```
This is the content of **values-minimal.yaml** supplying parameters to the above helm template command:
```
server:
  ha:
    raft:
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 0
          tls_cert_file = "/vault/userconfig/vault-tls/vault.crt"
          tls_key_file  = "/vault/userconfig/vault-tls/vault.key"
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}
```
Please find attached the resulting **vault-all.yaml** file.

**Comment by jasonodonnell** [comment]
Hi @manderson-it, the [securityContext's are disabled on OpenShift](https://github.com/hashicorp/vault-helm/blob/master/templates/server-statefulset.yaml).  The reason for this is OpenShift runs pods with arbitrary UID and GID 0.

We might just need to remove those specific security contexts so OpenShift can add them.  @tvoran

**Comment by jasonodonnell** [comment]
Perhaps something like this:

```
      securityContext:
        runAsNonRoot: true
        {{- if not .Values.global.openshift }}
        runAsGroup: {{ .Values.server.gid | default 1000 }}
        runAsUser: {{ .Values.server.uid | default 100 }}
        fsGroup: {{ .Values.server.gid | default 1000 }}
        {{- end }}
```
