### ISSUE TITLE
How can I replace left and right delimiters 

### ISSUE THREAD

**Issue by ramanNarasimhan77** [hashicorp/vault-helm#348]
Hello,

I have recently installed vault-helm chart in ha mode with consul backend.

I am attempting to use vault to securely inject secrets in argo workflow. My workflow has the following annotations where
"{{workflow.parameters.vault-gitcreds-secret}}" & "{{workflow.parameters.vault-auth-role}}" are go templates that argo replaces on runtime based on the workflow parameters vault-gitcreds-secret and vault-auth-role

The "{{workflow.parameters.vault-gitcreds-secret}}" under inject-template however is not getting rendered by argo since it is enclosed by another template.

Is it possible to override default delimiters and specify different delimiters for vault template so that I can use something like ${ and }$ so that argo workflow replace logic can work?

```
metadata:      
    annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-.git-credentials: "{{workflow.parameters.vault-gitcreds-secret}}"
        vault.hashicorp.com/secret-volume-path: "/home/app-user"
        vault.hashicorp.com/role: "{{workflow.parameters.vault-auth-role}}"
        vault.hashicorp.com/agent-inject-template-.git-credentials: |
          {{- with secret "{{workflow.parameters.vault-gitcreds-secret}}" -}}
            {{ .Data.data.gitcreds }}
          {{- end }}
```

P.S. - I  have also created [this](https://github.com/argoproj/argo/issues/3319) issue in argo github hoping that probably there is some workaround for this that I have overlooked
