### ISSUE TITLE
alb Ingress - http to https redirection.

### ISSUE THREAD

**Issue by davorceman** [hashicorp/vault-helm#361]
**Is your feature request related to a problem? Please describe.**
I can't create alb ingress with the ssl redirection. Currently after deploying with this in my vaules file
```
  ingress:
    enabled: true
    labels: {}
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: ${ingress_scheme}
      alb.ingress.kubernetes.io/healthcheck-path: /v1/sys/health
      alb.ingress.kubernetes.io/success-codes: 429,200
      alb.ingress.kubernetes.io/security-groups: ${ingress_security_group}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: ${ingress_certificate_arn}
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/tags: ${ingress_tags}
    hosts:
      - host: ${ingress_host}
        paths: ["/*"]
  service:
    type: NodePort
```
... there is no redirection from http to https

**Describe the solution you'd like**
I want to have possibility to add one more path in rules for SSL redirection.
Currently code is
```
  rules:
  {{- range .Values.server.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}
```
and I don't see the way to add
```
- path: /*
  backend:
    serviceName: ssl-redirect
    servicePort: use-annotation
```
as a second path to the same host.
