### ISSUE TITLE
Cannot add annotations to Service object.

### ISSUE THREAD

**Issue by echoboomer** [hashicorp/vault-helm#365]
**Describe the bug**
When trying to add `Service` annotations via `server.service.annotations`, the operation fails regardless of the actual content of the annotations, even when following the `yaml` formatting options in this guide [here](https://www.vaultproject.io/docs/platform/k8s/helm/configuration#service). I tried this with properly formatted AWS-specific ELB annotations and with simple test annotations.

**To Reproduce**
1. Set `server.service.annotations` field
2. Attempt to install chart

Other useful info to include: vault pod logs, `kubectl describe statefulset vault` and `kubectl get statefulset vault -o yaml` output

```
error="rpc error: code = InvalidArgument desc = application spec is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code
...
failed exit status 1: coalesce.go:192: warning: cannot overwrite table with non table for annotations (map[])\nError: YAML parse error on vault/templates/server-ha-active-service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field .metadata.annotations of type map[string]string\n\nUse --debug flag to render out invalid YAML"
```

**Expected behavior**
The annotations should be applied to the `Service`.

**Environment**
* Kubernetes version: `v1.15.11-eks-14f01f`
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
  * Other configuration options or runtime services (istio, etc.): Nothing that should interfere with Vault.
* vault-helm version: `v0.5.0`

Chart values:

```yaml
        server:
          ha:
            enabled: true
            raft:
              enabled: true
          extraEnvironmentVars:
            VAULT_SEAL_TYPE: awskms
          extraSecretEnvironmentVars:
            <redacted>
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:1234567890:certificate/foo"
              service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
              external-dns.alpha.kubernetes.io/hostname: "vault.foo-internal.com"
        injector:
          enabled: true
        ui:
          enabled: true
```

**Additional context**
