### ISSUE TITLE
Vault not booting on AWS using awskms seal

### ISSUE THREAD

**Issue by marcofranssen** [hashicorp/vault-helm#368]
I'm deploying vault on EKS using following `values.yaml`.

```yml
server:
  image:
    tag: 1.5.0

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      service_registration "kubernetes" {}

      seal "awskms" {
        kms_key_id = "my-kms-key-id"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce

  ui:
    enabled: true
    serviceType: LoadBalancer
```

I'm continuously getting the following error.

```bash
$ vault status
Error checking seal status: Get "http://127.0.0.1:8200/v1/sys/seal-status": dial tcp 127.0.0.1:8200: connect: connection refused
```

This prevents me from initializing vault.

My KMS key does have the required policy so the EKS node can access it.

```bash
$ aws kms list-grants --key-id my-kms-key-id
{
    "Grants": [
        {
            "KeyId": "arn:aws:kms:eu-west-1:759729069112:key/my-kms-key-id",
            "GrantId": "756045c9f34bc690c9a1fcb225de614566355a9d1aa2d5f92dbb547abca3bcc2",
            "Name": "k8s-worker-nodes-vault",
            "CreationDate": "2020-08-04T10:06:37+02:00",
            "GranteePrincipal": "arn:aws:iam::759729069112:role/dctna-dev-cluster20200804080403426400000007",
            "IssuingAccount": "arn:aws:iam::759729069112:root",
            "Operations": [
                "Decrypt",
                "Encrypt",
                "DescribeKey"
            ]
        }
    ]
}
```

Is there a way to debug?

I have also tried using the default image tag `1.4.2`, also this one fails.

**Comment by cbohrtarwater** [comment]
I've got it working with this awskms block:

```
seal "awskms" {
   region      = "us-east-1"
   kms_key_id  = "QQQQQQQQ"
}
```

Maybe see if adding the region helps?

**Comment by echoboomer** [comment]
I actually completely bypassed the `awskms` block in the config and instead used the vars:

```yaml
          extraEnvironmentVars:
            VAULT_SEAL_TYPE: awskms
          extraSecretEnvironmentVars:
            - envName: AWS_ACCESS_KEY_ID
              secretName: vault-aws-auth
              secretKey: VAULT_AWS_ACCESS_KEY_ID
            - envName: AWS_SECRET_ACCESS_KEY
              secretName: vault-aws-auth
              secretKey: VAULT_AWS_SECRET_ACCESS_KEY
            - envName: AWS_REGION
              secretName: vault-aws-auth
              secretKey: VAULT_AWS_REGION
            - envName: VAULT_AWSKMS_SEAL_KEY_ID
              secretName: vault-aws-auth
              secretKey: VAULT_AWSKMS_SEAL_KEY_ID
```

**Comment by tvoran** [comment]
@echoboomer As @cbohrtarwater mentioned, I've usually seen region specified in the awskms config block.

As for debugging it, we're working on adding more logging around the awskms credential code, but in the meantime check the logs of the vault container? vault should eventually log the error it encountered and which credentials it's using.

**Comment by marcofranssen** [comment]
I have tried to provide the region both in config as well using environment variables. There are no kube logs neither logs in /vault/logs within the container.

Running below in the pod.

```bash
$ vault status
Error checking seal status: Get "http://127.0.0.1:8200/v1/sys/seal-status": dial tcp 127.0.0.1:8200: connect: connection refused
```

The helm value I use are the following.

```yaml
server:
  standalone:
    enabled: true

  extraEnvironmentVars:
    VAULT_SEAL_TYPE: awskms
    VAULT_AWS_REGION: $VAULT_KMS_KEY_ID
    VAULT_AWSKMS_SEAL_KEY_ID: $AWS_REGION

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce

  service:
    enabled: true

  ui:
    enabled: true
    serviceType: LoadBalancer
```

Also tried this

```yaml
server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      service_registration "kubernetes" {}

      seal "awskms" {
        kms_key_id = "$VAULT_KMS_KEY_ID"
        region = "$AWS_REGION"
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce

  service:
    enabled: true

  ui:
    enabled: true
    serviceType: LoadBalancer
```

**Comment by marcofranssen** [comment]
When explicitly setting the following environment values it works.

```yaml
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
```

According to documentation it should also be possible to run without these and take the role principle.
https://www.vaultproject.io/docs/configuration/seal/awskms#kms_key_id

We are sure we managed to get it working once, but can't reproduce.

**Comment by tvoran** [comment]
So vault should eventually crash and log which AWS credentials it's trying to use for auto-unseal, and why they failed. Something like this:

```
Error parsing Seal configuration: error fetching AWS KMS wrapping key information: AccessDeniedException: User: <role-arn> is not authorized to perform: kms:DescribeKey on resource: <kms-arn>
    status code: 400, request id: f273c40f-ff81-47f4-b0d6-0898161a287d
```

I have noticed that sometimes it takes a few minutes for the AWS auth to fail, the vault pod then exits with an error, and then the pod will restart. So you may need to use something like `kubectl logs vault-0 --previous` or k9s to see the log easily.

**Comment by tvoran** [comment]
In case it helps, we added more debug logging to the awskms auto-unseal credential code in Vault 1.6: https://github.com/hashicorp/vault/pull/9794

And as of Vault 1.5.5 and 1.6.0 we also decreased the timeout in the AWS client so that a failure to authenticate returns faster: https://www.vaultproject.io/docs/upgrading/upgrade-to-1.5.0#aws-instance-metadata-timeout

**Comment by cabrinha** [comment]
Does EKS auto-unseal work with IAM Roles for Service Accounts?

**Comment by tvoran** [comment]
@cabrinha Yes, Vault's auto-unseal works with EKS and IAM Roles for Service Accounts. Though it looks like this was unsealed using shamir, then started up with auto-unseal configured. I'd suggest taking a look at the migration docs: https://www.vaultproject.io/docs/concepts/seal#seal-migration

**Comment by cabrinha** [comment]
> @cabrinha Yes, Vault's auto-unseal works with EKS and IAM Roles for Service Accounts. Though it looks like this was unsealed using shamir, then started up with auto-unseal configured. I'd suggest taking a look at the migration docs: https://www.vaultproject.io/docs/concepts/seal#seal-migration

Why was this unsealed using Shamir? I've been deleting the statefulset and re-creating it to no avail. How can I get vault to startup without shamir in the first place?

**Comment by tvoran** [comment]
Yeah, if you just want auto-unseal, set an awskms seal config block:

```hcl
seal "awskms" {
  region     = "us-west-2"
  kms_key_id = "alias/my-vault-role-key"
}
```

And either add the role annotation to the service account in the chart values:

```yaml
server:
    serviceAccount:
        annotations:
            eks.amazonaws.com/role-arn: <role-arn>
```

or specify which existing service account to use: https://www.vaultproject.io/docs/platform/k8s/helm/configuration#serviceaccount

```yaml
server:
    serviceAccount:
        create: false
        name: vault
```

EKS will set AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables in the pod if IRSA is setup correctly, and the awskms logic will attempt to use those credentials for accessing the KMS (turn on debug logging for more info in that part of the process). Then run `vault operator init`.

(If you haven't see this tutorial you may also find it useful: https://learn.hashicorp.com/tutorials/vault/autounseal-aws-kms)

**Comment by worldofgeese** [comment]
> Yeah, if you just want auto-unseal, set an awskms seal config block:
> 
> ```terraform
> seal "awskms" {
>   region     = "us-west-2"
>   kms_key_id = "alias/my-vault-role-key"
> }
> ```
> 
> And either add the role annotation to the service account in the chart values:
> 
> ```yaml
> server:
>   serviceAccount:
>     annotations:
>       eks.amazonaws.com/role-arn: <role-arn>
> ```
> 
> or specify which existing service account to use: https://www.vaultproject.io/docs/platform/k8s/helm/configuration#serviceaccount
> 
> ```yaml
> server:
>   serviceAccount:
>     create: false
>     name: vault
> ```
> 
> EKS will set AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables in the pod if IRSA is setup correctly, and the awskms logic will attempt to use those credentials for accessing the KMS (turn on debug logging for more info in that part of the process). Then run `vault operator init`.
> 
> (If you haven't see this tutorial you may also find it useful: https://learn.hashicorp.com/tutorials/vault/autounseal-aws-kms)

I have IRSA working for `cluster_autoscaler`. I added an additional statement to the role (since it was already attached to the cluster):
```hcl
  statement {
    sid    = "vaultKmsUnseal"
    effect = "Allow"

    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:DescribeKey",
    ]

    resources = ["*"]
  }
```

`vault-chart-values.yaml`:
```yaml
global:
  enabled: true

server:
  serviceAccount:
    annotations:
      # attach cluster-autoscaler role so Vault can interact with, and unlock, our vault
      eks.amazonaws.com/role-arn: arn:aws:iam::472409228388:role/cluster-autoscaler
  extraEnvironmentVars:
    VAULT_SEAL_TYPE: awskms
  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: eks-creds
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: eks-creds
      secretKey: AWS_SECRET_ACCESS_KEY
    - envName: AWS_REGION
      secretName: eks-creds
      secretKey: VAULT_AWS_REGION
    - envName: VAULT_AWSKMS_SEAL_KEY_ID
      secretName: eks-creds
      secretKey: VAULT_AWSKMS_SEAL_KEY_ID

  ha:
    enabled: true
```

I `kubectl port-forward -n vault vault-0 8200:8200`. `vault status` shows:
```
Key                      Value
---                      -----
Recovery Seal Type       awskms
Initialized              false
Sealed                   true
Total Recovery Shares    0
Threshold                0
Unseal Progress          0/0
Unseal Nonce             n/a
Version                  1.6.1
Storage Type             consul
HA Enabled               true
```

So far, so good. Here's where I encounter difficulties.
`vault operator init -key-shares=5 -key-threshold=3` gives me the following permissions error:
```
Error initializing: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/init
Code: 400. Errors:

* failed to store keys: failed to encrypt keys for storage: error encrypting dat
a: AccessDeniedException: User: arn:aws:iam::472409228388:root is not authorized
 to perform: kms:Encrypt on resource: arn:aws:kms:eu-north-1:472409228388:key/26
0757fd-c5e8-49b4-972d-66fb5a366a1e
        status code: 400, request id: e901af52-f9a1-4016-ba85-5818ab770bdb
```

EKS sets `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` correctly:
![image](https://user-images.githubusercontent.com/59834693/104816362-f6ec3000-581a-11eb-85a0-51351c24f853.png)

What am I doing wrong here?
