### ISSUE TITLE
[vault-helm] Add registry for image in values.yaml

### ISSUE THREAD

**Issue by qtomato3** [hashicorp/vault-helm#423]
**Is your feature request related to a problem? Please describe.**
Current `values.yaml` doesn't allow other image registry to be specified. This leads to default `docker.io` is used and this affects our pipelines due to public pull rate limit recently imposed by Docker.

**Describe the solution you'd like**
1. Add registry to image declaration under `vault-helm/values.yaml`
```
server:
  image:
    registry: docker.io    // <<<--- added
    repository: "vault"
    tag: "1.5.4"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent
```
2. Update related usage under templates/, e.g. `vault-helm/templates/server-statefulset.yaml`
```
      containers:
        - name: vault
          {{ template "vault.resources" . }}
          image: {{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default "latest" }}

```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank you

**Comment by jasonodonnell** [comment]
Hi @qtomato3, the registry is actually built into the repository of the image. Since no registry is specified, it defaults to `docker.io`, but you can override it.

So for example, to pull from a GCR registry:

```
server:
  image:
    repository: "gcr.io/vault-helm-dev/hashicorp/vault"
    tag: "1.5.4"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent
```
