### ISSUE TITLE
Add Volume Selectors when binding PVC

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/vault-helm#431]
RabbitMQ Chart already has this feature.

https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml#L300-L307

```
persistence:
  storageClass: "manual"
  selector:
    matchLabels:
      app: rabbitmq
  size: {{replicaSize}}
```

**Comment by rkennedy-tpl** [comment]
is storageClass currently being respected?

I traced the code to => https://github.com/hashicorp/vault-helm/blob/7a71c0fec489759ad7293869e816ae6ca34c403a/templates/_helpers.tpl#L188-L190

but the following values isn't doing what I expect...

```yaml
server:
  ha:
    enabled: true
    raft:
      enabled: true
  dataStorage:
    enabled: true
    storageClass: "efs-sc"
```

that's `server.dataStorage.storageClass` being set, right? but it's still making gp2 volumes when run.
