### ISSUE TITLE
Secret injection fails without namespaceSelector

### ISSUE THREAD

**Issue by logileifs** [hashicorp/vault-helm#438]
**Describe the bug**
In the [docs](https://www.vaultproject.io/docs/platform/k8s/injector/installation#namespace-selector) it says: 
> By default, the Vault Agent Injector will process all namespaces in Kubernetes except the system namespaces kube-system and kube-public. 

However when I run the agent-injector with no namespaceSelector specified and pods with `vault.hashicorp.com/agent-inject: true` the secrets do not get injected into the pods but it works when I add a namespaceSelector and a label on the relevant namespace.

**To Reproduce**
1. Install chart
2. Start a pod that should have a secret injected
3. Shell into the pod and see that the secrets are not there

**Expected behavior**
Secrets should be injected to all pods with `vault.hashicorp.com/agent-inject: true` in all namespaces when no namespaceSelector is specified

**Environment**
* Kubernetes version: v1.18.8
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): kubernetes in docker for mac
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version: 0.8.0

Chart values:

```yaml
vault:
  #injector:
  #  namespaceSelector:
  #    matchLabels:
  #      sidecar-injector: enabled

  server:
    serviceAccount:
      # Specifies whether a service account should be created
      create: false
    # Extra labels to attach to the server pods
    # This should be a YAML map of the labels to apply to the server pods
    extraLabels:
      network/allow-internet-access: "true"
      network/allow-database-access: "true"

    extraSecretEnvironmentVars:
      # Without this, the production defaults take precedence over the local overrides above.
      - envName: VAULT_PG_CONNECTION_URL
        secretName: db-credentials-vault
        secretKey: POSTGRES_URL

    ha:
      enabled: true
      replicas: 2
```

**Additional context**
no additional context
