### ISSUE TITLE
AKS disable_mlock = false is not working

### ISSUE THREAD

**Issue by apolegoshko** [hashicorp/vault-helm#447]
**Describe the bug**
Gettin an error that vault cannot start due mlock.

```log
Error initializing core: Failed to lock memory: cannot allocate memory

This usually means that the mlock syscall is not available.
Vault uses mlock to prevent memory from being swapped to
disk. This requires root privileges as well as a machine
that supports mlock. Please enable mlock on your system or
disable Vault from using it. To disable Vault from using it,
set the `disable_mlock` configuration option in your configuration
file.
2021-01-19T11:08:26.311Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=

```

**To Reproduce**
1. Install chart
2. Run vault init, unseal
3. See error above

```log
k describe statefulsets.apps vault-ha
Name:               vault-ha
Namespace:          default
CreationTimestamp:  Wed, 13 Jan 2021 09:55:49 +0100
Selector:           app.kubernetes.io/instance=vault-ha,app.kubernetes.io/name=vault,component=server
Labels:             app.kubernetes.io/instance=vault-ha
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=vault
                    fluxcd.io/sync-gc-mark=sha256.QfnYGlXgf4p8ZYRg5c0RI6gpq1icPs8p3TzLEhU_ptg
Annotations:        fluxcd.io/sync-checksum: f06e619baae74c47929c775899dbc1462b410a3f
Replicas:           2 desired | 2 total
Update Strategy:    OnDelete
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/instance=vault-ha
                    app.kubernetes.io/name=vault
                    component=server
                    helm.sh/chart=vault-0.9.0
  Service Account:  vault-ha
  Containers:
   vault:
    Image:       vault:1.6.1
    Ports:       8200/TCP, 8201/TCP, 8202/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -ec
    Args:
      cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;
      [ -n "${HOST_IP}" ] && sed -Ei "s|HOST_IP|${HOST_IP?}|g" /tmp/storageconfig.hcl;
      [ -n "${POD_IP}" ] && sed -Ei "s|POD_IP|${POD_IP?}|g" /tmp/storageconfig.hcl;
      [ -n "${HOSTNAME}" ] && sed -Ei "s|HOSTNAME|${HOSTNAME?}|g" /tmp/storageconfig.hcl;
      [ -n "${API_ADDR}" ] && sed -Ei "s|API_ADDR|${API_ADDR?}|g" /tmp/storageconfig.hcl;
      [ -n "${TRANSIT_ADDR}" ] && sed -Ei "s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g" /tmp/storageconfig.hcl;
      [ -n "${RAFT_ADDR}" ] && sed -Ei "s|RAFT_ADDR|${RAFT_ADDR?}|g" /tmp/storageconfig.hcl;
      /usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl 
      
    Readiness:  exec [/bin/sh -ec vault status -tls-skip-verify] delay=5s timeout=3s period=5s #success=1 #failure=2
    Environment:
      HOST_IP:               (v1:status.hostIP)
      POD_IP:                (v1:status.podIP)
      VAULT_K8S_POD_NAME:    (v1:metadata.name)
      VAULT_K8S_NAMESPACE:   (v1:metadata.namespace)
      VAULT_ADDR:           http://127.0.0.1:8200
      VAULT_API_ADDR:       http://$(POD_IP):8200
      SKIP_CHOWN:           true
      SKIP_SETCAP:          true
      HOSTNAME:              (v1:metadata.name)
      VAULT_CLUSTER_ADDR:   https://$(HOSTNAME).vault-ha-internal:8201
      HOME:                 /home/vault
    Mounts:
      /home/vault from home (rw)
      /vault/config from config (rw)
      /vault/data from data (rw)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      vault-ha-config
    Optional:  false
   home:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Volume Claims:
  Name:          data
  StorageClass:  
  Labels:        <none>
  Annotations:   <none>
  Capacity:      1Gi
  Access Modes:  [ReadWriteOnce]

```

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    fluxcd.io/sync-checksum: f06e619baae74c47929c775899dbc1462b410a3f
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{"fluxcd.io/sync-checksum":"f06e619baae74c47929c775899dbc1462b410a3f"},"labels":{"app.kubernetes.io/instance":"vault-ha","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"vault","fluxcd.io/sync-gc-mark":"sha256.QfnYGlXgf4p8ZYRg5c0RI6gpq1icPs8p3TzLEhU_ptg"},"name":"vault-ha","namespace":"default"},"spec":{"podManagementPolicy":"Parallel","replicas":2,"selector":{"matchLabels":{"app.kubernetes.io/instance":"vault-ha","app.kubernetes.io/name":"vault","component":"server"}},"serviceName":"vault-ha-internal","template":{"metadata":{"labels":{"app.kubernetes.io/instance":"vault-ha","app.kubernetes.io/name":"vault","component":"server","helm.sh/chart":"vault-0.9.0"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchLabels":{"app.kubernetes.io/instance":"vault-ha","app.kubernetes.io/name":"vault","component":"server"}},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;\n[ -n \"${HOST_IP}\" ] \u0026\u0026 sed -Ei \"s|HOST_IP|${HOST_IP?}|g\" /tmp/storageconfig.hcl;\n[ -n \"${POD_IP}\" ] \u0026\u0026 sed -Ei \"s|POD_IP|${POD_IP?}|g\" /tmp/storageconfig.hcl;\n[ -n \"${HOSTNAME}\" ] \u0026\u0026 sed -Ei \"s|HOSTNAME|${HOSTNAME?}|g\" /tmp/storageconfig.hcl;\n[ -n \"${API_ADDR}\" ] \u0026\u0026 sed -Ei \"s|API_ADDR|${API_ADDR?}|g\" /tmp/storageconfig.hcl;\n[ -n \"${TRANSIT_ADDR}\" ] \u0026\u0026 sed -Ei \"s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g\" /tmp/storageconfig.hcl;\n[ -n \"${RAFT_ADDR}\" ] \u0026\u0026 sed -Ei \"s|RAFT_ADDR|${RAFT_ADDR?}|g\" /tmp/storageconfig.hcl;\n/usr/local/bin/docker-entrypoint.sh vault server -config=/tmp/storageconfig.hcl \n"],"command":["/bin/sh","-ec"],"env":[{"name":"HOST_IP","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"VAULT_K8S_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"VAULT_K8S_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"VAULT_ADDR","value":"http://127.0.0.1:8200"},{"name":"VAULT_API_ADDR","value":"http://$(POD_IP):8200"},{"name":"SKIP_CHOWN","value":"true"},{"name":"SKIP_SETCAP","value":"true"},{"name":"HOSTNAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"VAULT_CLUSTER_ADDR","value":"https://$(HOSTNAME).vault-ha-internal:8201"},{"name":"HOME","value":"/home/vault"}],"image":"vault:1.6.1","imagePullPolicy":"IfNotPresent","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","sleep 5 \u0026\u0026 kill -SIGTERM $(pidof vault)"]}}},"name":"vault","ports":[{"containerPort":8200,"name":"http"},{"containerPort":8201,"name":"https-internal"},{"containerPort":8202,"name":"http-rep"}],"readinessProbe":{"exec":{"command":["/bin/sh","-ec","vault status -tls-skip-verify"]},"failureThreshold":2,"initialDelaySeconds":5,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":3},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["IPC_LOCK"]}},"volumeMounts":[{"mountPath":"/vault/data","name":"data"},{"mountPath":"/vault/config","name":"config"},{"mountPath":"/home/vault","name":"home"}]}],"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":100},"serviceAccountName":"vault-ha","terminationGracePeriodSeconds":10,"volumes":[{"configMap":{"name":"vault-ha-config"},"name":"config"},{"emptyDir":{},"name":"home"}]}},"updateStrategy":{"type":"OnDelete"},"volumeClaimTemplates":[{"metadata":{"name":"data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]}}
  creationTimestamp: "2021-01-13T08:55:49Z"
  generation: 9
  labels:
    app.kubernetes.io/instance: vault-ha
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    fluxcd.io/sync-gc-mark: sha256.QfnYGlXgf4p8ZYRg5c0RI6gpq1icPs8p3TzLEhU_ptg
  name: vault-ha
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: vault-ha
      app.kubernetes.io/name: vault
      component: server
  serviceName: vault-ha-internal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: vault-ha
        app.kubernetes.io/name: vault
        component: server
        helm.sh/chart: vault-0.9.0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: vault-ha
                app.kubernetes.io/name: vault
                component: server
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - "cp /vault/config/extraconfig-from-values.hcl /tmp/storageconfig.hcl;\n[
          -n \"${HOST_IP}\" ] && sed -Ei \"s|HOST_IP|${HOST_IP?}|g\" /tmp/storageconfig.hcl;\n[
          -n \"${POD_IP}\" ] && sed -Ei \"s|POD_IP|${POD_IP?}|g\" /tmp/storageconfig.hcl;\n[
          -n \"${HOSTNAME}\" ] && sed -Ei \"s|HOSTNAME|${HOSTNAME?}|g\" /tmp/storageconfig.hcl;\n[
          -n \"${API_ADDR}\" ] && sed -Ei \"s|API_ADDR|${API_ADDR?}|g\" /tmp/storageconfig.hcl;\n[
          -n \"${TRANSIT_ADDR}\" ] && sed -Ei \"s|TRANSIT_ADDR|${TRANSIT_ADDR?}|g\"
          /tmp/storageconfig.hcl;\n[ -n \"${RAFT_ADDR}\" ] && sed -Ei \"s|RAFT_ADDR|${RAFT_ADDR?}|g\"
          /tmp/storageconfig.hcl;\n/usr/local/bin/docker-entrypoint.sh vault server
          -config=/tmp/storageconfig.hcl \n"
        command:
        - /bin/sh
        - -ec
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: VAULT_K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VAULT_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: VAULT_API_ADDR
          value: http://$(POD_IP):8200
        - name: SKIP_CHOWN
          value: "true"
        - name: SKIP_SETCAP
          value: "true"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VAULT_CLUSTER_ADDR
          value: https://$(HOSTNAME).vault-ha-internal:8201
        - name: HOME
          value: /home/vault
        image: vault:1.6.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5 && kill -SIGTERM $(pidof vault)
        name: vault
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        - containerPort: 8201
          name: https-internal
          protocol: TCP
        - containerPort: 8202
          name: http-rep
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - vault status -tls-skip-verify
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - IPC_LOCK
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/data
          name: data
        - mountPath: /vault/config
          name: config
        - mountPath: /home/vault
          name: home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
      serviceAccount: vault-ha
      serviceAccountName: vault-ha
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          name: vault-ha-config
        name: config
      - emptyDir: {}
        name: home
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: vault-ha-5b68f8774c
  observedGeneration: 9
  readyReplicas: 2
  replicas: 2
  updateRevision: vault-ha-5b68f8774c
  updatedReplicas: 2
```

**Expected behavior**
I'm expeting that vault should start with config below

```hcl
    disable_mlock = false
    ui = true
    
    listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
    }
    
    storage "raft" {
        path = "/vault/data"
    }
    
    service_registration "kubernetes" {}
```

**Environment**
* Kubernetes version: 
  * Azure AKS with default configuration

* vault-helm version:
- chart version: 0.9.0
- application version: v1.6.1

Chart values:

```yaml
injector:
    enabled: false

server:
    standalone:
      enabled: "false"
    dataStorage:
      size: 1Gi
    ha:
      replicas: 2
      enabled: true
      disruptionBudget:
        maxUnavailable: 1
      raft:
        enabled: true
        config: |
           disable_mlock = false
            ui = true

            listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
            }

            storage "raft" {
                path = "/vault/data"
            }

            service_registration "kubernetes" {}
```

**Additional context**
Running vault under managing of flux.
