### ISSUE TITLE
Vault Pods failing health checks, certificate errors.

### ISSUE THREAD

**Issue by echoboomer** [hashicorp/vault-helm#491]
**Describe the bug**
After upgrading to `0.9.1`, we have encountered a situation where the active Vault `Pod` will start to fail its health checks and become unavailable. It will not fail over in this scenario. We have to delete the `Pod` in order to cause a failover, and then things proceed normally. Eventually, the issue will happen on the `Pod` that has now become active. We have seen this happen twice in the past two days.

We see this from the perspective of the agent's `init` container on `Pods` that are trying to create while this condition is happening:

```
2021-04-06T12:10:21.463Z [ERROR] auth.handler: error authenticating: error="Put "https://10.13.3.45:8200/v1/auth/kubernetes/login": x509: certificate is valid for 127.0.0.1, not 10.13.3.45" backoff=1
.250620005
2021-04-06T12:10:22.714Z [INFO]  auth.handler: authenticating
2021-04-06T12:10:22.785Z [ERROR] auth.handler: error authenticating: error="Put "https://10.13.3.45:8200/v1/auth/kubernetes/login": x509: certificate is valid for 127.0.0.1, not 10.13.3.45" backoff=2
.6331120759999997
2021-04-06T12:10:25.418Z [INFO]  auth.handler: authenticating
2021-04-06T12:11:25.419Z [ERROR] auth.handler: error authenticating: error="context deadline exceeded" backoff=1.047931231
```

From the perspective of the Vault `Pod`, we see errors like this:

```
2021-04-06T12:12:44.766Z [INFO]  http: TLS handshake error from 10.13.60.123:56740: remote error: tls: bad certificate
2021-04-06T12:12:44.891Z [WARN]  core.cluster-listener: no TLS config found for ALPN: ALPN=[req_fw_sb-act_v1]
```

We use this guide to generate our certificate for server: https://www.vaultproject.io/docs/platform/k8s/helm/examples/standalone-tls

We also use this guide to generate our certificate for the agent injector service: https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls

We have combined both of those into scripts that we run when Vault is instantiated in a given environment. We have used this process for almost a year and have never had this issue. The issue has only started happening since we bumped to chart version `0.9.1` and Vault version `1.6.2`.

Again, the only reason we bumped to this version was to get support for multiple replicas for the agent injector service since this was a critical enhancement for us. Because we define our own TLS certificates, we have configure our Vault values for Helm to turn off the leader elector logic for the agent injector. I'm not sure if this was the right move, but this was the only way to get this to work.

**To Reproduce**
1. Upgraded chart from `0.8.0` to `0.9.1` to get the added benefit of multiple replicas for the agent injector service.
2. Let Vault run.
3. Eventually the issue will occur.
4. Delete the `Pod` so another one will take over.
5. Eventually that `Pod` encounters the issue.
6. Repeat.

**Expected behavior**
Vault runs normally without us needing to intervene. At a minimum, the failed `Pod` should cause another one to take over so we don't have to delete them manually.

**Environment**
* Kubernetes version: `v1.18.16-gke.500`
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): GKE
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version: `0.9.1`

Chart values:

```yaml
global:
  tlsDisable: false
injector:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
  enabled: true
  certs:
    secretName: vault-agent-injector-tls
    caBundle: <foo>
    certName: vault-injector.crt
    keyName: vault-injector.key
  leaderElector:
    enabled: false
  replicas: 3
server:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: vault-sa@project-id.iam.gserviceaccount.com
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/vault.ca
  extraVolumes:
    - type: secret
      name: vault-server-tls
      path: '/vault/userconfig'
  ha:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        address            = "[::]:8200"
        cluster_address    = "[::]:8201"
        tls_disable        = 0
        tls_cert_file      = "/vault/userconfig/vault-server-tls/vault.crt"
        tls_key_file       = "/vault/userconfig/vault-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-server-tls/vault.ca"
        tls_min_version    = "tls12"
        telemetry {
          unauthenticated_metrics_access = true
        }
      }

      seal "gcpckms" {
        crypto_key  = "vault-unseal"
        key_ring    = "vault"
        project     = "project"
        region      = "global"
      }

      service_registration "kubernetes" {}

      storage "gcs" {
        bucket     = "bucket"
        ha_enabled = "true"
      }

      telemetry {
        prometheus_retention_time = "72h"
      }
ui:
  enabled: true
```
