### ISSUE TITLE
vault-injector: support injector.leaderElector.resources configuration

### ISSUE THREAD

**Issue by SohamJ** [hashicorp/vault-helm#524]
**Is your feature request related to a problem? Please describe.**
> This is a feature request

## Background

Enabling the `injector.leaderElector` configuration along with multiple replicas using the `injector.replicas` configuration adds a new `leader-elector` sidecar container to the injector pods. 

## Issue

For environments with `ResourceQuota` set on their namespaces, every pod in the namespace needs to explicitly define requests and limits. Currently, the `leader-elector` sidecars do *not* have that capability. This results in Kubernetes blocking the creation of pods:

```shell
# Trimmed output
kubectl describe rs vault-injector-ddc486cf9 

Containers:
   sidecar-injector:
    Limits:
      cpu:     250m
      memory:  256Mi
    Requests:
      cpu:      250m
      memory:   256Mi
 
   leader-elector:
    Image:      gcr.io/google_containers/leader-elector:0.4
    # <NO RESOURCE LIMITS SET>

Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                    From                   Message
  ----     ------        ----                   ----                   -------
  Warning  FailedCreate  7m20s                  replicaset-controller  Error creating: pods "vault-injector-ddc486cf9-jdx9w" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

**Describe the solution you'd like**
Support a new `injector.leaderElector.resources` configuration map allowing users to define the resource requests and limits. This can be similar to the `injector.resources` config:

```yaml
injector:
  leaderElector:
    resources:
      requests:
        memory: '100Mi'
      limits:
        memory: '100Mi'
```

Alternatively, the `injector.resources` property *could* be used for both the containers in the pod, although this might lead to resource wastage if they don't consume equivalent amounts of resources (which I assume they don't)

**Describe alternatives you've considered**
A temporary alternative was to unset (or delete if manually configured) the namespace resourcequota works fine:

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard: {}
```

Another alternative of manually creating the tls.certs for Mutating Webhooks is an option, but was not pursued to favor auto-tls and avoid additional maintainance of the certs

**Additional context**

Our environments set a default ResourceQuota for each namespace since the clusters are multi-tenant. This request is to support the currently-adopted defaults. 

Since the injector pods do not consume too many resources and will not increase it dynamically, the alternative described should be fine for now. That said, allowing this configuration will have an added benefit of fine-tuning the resources consumed by the service

Kubernetes information:

```
k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7+icp-ee", GitCommit:"80138fdc8512052849245e92fd02732070c4247d", GitTreeState:"clean", BuildDate:"2020-04-21T07:17:34Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Vault helm chart - 0.11.0
Vault helm values (trimmed) -

```yaml
# https://www.vaultproject.io/docs/platform/k8s/helm/configuration
global:
  enabled: true
  tlsDisable: false

injector:
  enabled: true
  replicas: 2
  leaderElector:
    enabled: true
  resources:
    requests:
      memory: 100Mi
      cpu: 250m
    limits:
      memory: 100Mi
      cpu: 250m
```
