### ISSUE TITLE
Vault not able to Parse configMap in server.volumes

### ISSUE THREAD

**Issue by saurabhumathe** [hashicorp/vault-helm#550]
**Describe the bug**
 As mentioned in values file an additional volumes can be used with vault and these are rendered via toYaml rather than pre-processed. however, when we add configMap volume type helm is giving parsing error.

 volumes:
      -  name: unseal-volume
         configMap:
           name: { { template "vault.fullname" . } }-unseal-config
           defaultMode: 0420

Error: failed to parse .\values.yaml: error converting YAML to JSON: yaml: line 377: mapping values are not allowed in this context
**To Reproduce**
1. Install chart  - appVersion: 1.7.0 and make change to vaules file in server.volumes as shown below

 volumes:
      -  name: unseal-volume
         configMap:
           name: { { template "vault.fullname" . } }-unseal-config
           defaultMode: 0420

2. Run vault command --  helm install vault ./ -f .\values.yaml
3. See error (vault logs, etc.) --Error: failed to parse .\values.yaml: error converting YAML to JSON: yaml: line 375: did not find expected key

It looks like it is only accepting emptyDir volume type.

**Expected behavior**
chart should be installed with the new volume configured in values file.

**Environment**
* Kubernetes version: 
*Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0",
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.1+f06151f",

  * Distribution or cloud vendor - OpenShift
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version:
version: 0.11.0
appVersion: 1.7.0
Chart values:
File attached

```yaml
# Paste your user-supplied values here (`helm get values <release>`).

  extraVolumes: []

  # volumes is a list of volumes made available to all containers. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumes:
  #    - name: plugins
  #      emptyDir: {}
      -  name: unseal-volume
         configMap:
           name: { { template "vault.fullname" . } }-unseal-config
           defaultMode: 0420
  # volumeMounts is a list of volumeMounts for the main server container. These are rendered
  # via toYaml rather than pre-processed like the extraVolumes value.
  # The purpose is to make it easy to share volumes between containers.
  volumeMounts:
      - mountPath: /vault/userconfig/
        name: unseal-config
        readOnly: false  


# Be sure to scrub any sensitive values!
```

**Additional context**
