### ISSUE TITLE
PVC not correctly created

### ISSUE THREAD

**Issue by ckazimie** [hashicorp/vault-helm#553]
**Describe the bug**
PersistencVolumeClaims are not created correctly, they are lacking storageClassName even though the volumeClaimTemplates for the StatefulSet does get storageClassName correctly set.

 ```
 volumeClaimTemplates:
    - metadata:
        name: data
      
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-storage

```

**To Reproduce**
Use the following values.yml

```
server:
  ha:
    enabled: true
    raft: 
      enabled: true
  dataStorage:
    enabled: true
    storageClass: local-storage

```
and deploy the chart
```
helm install --namespace vault --create-namespace vault hashicorp/vault -f values.yaml

kubectl -n vault get pvc
NAME           STATUS    VOLUME                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data-vault-0   Pending                                                                                                            26m
data-vault-1   Pending                                                                                                            26m
data-vault-2   Pending                                                                                                            26m

```

PVCs do not get bount as they lack storageClass

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  name: data-vault-0
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
```

When I delete PVCs and add the storageClass: local-storage they get bound PVs.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  name: data-vault-0
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-storage
```
**Expected behavior**
PVC should be created with storageClass as storageClassName is specified in the template for statefulSet

**Environment**
* Kubernetes version: 1.19.11
* helm 3.4.2 
* vault-helm version:  chart vault-0.12.0   app:1.7.2

Chart values:
as above.
```yaml
# Paste your user-supplied values here (`helm get values <release>`).
# Be sure to scrub any sensitive values!
```
My storage class definition. 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
**Additional context**
