### ISSUE TITLE
nodeSelector unused when server.dev.enabled is true

### ISSUE THREAD

**Issue by smarsh-tim** [hashicorp/vault-helm#556]
**Describe the bug**
The helper that sets the nodeSelector for the server pods will be skipped when the mode is set to `dev`.
https://github.com/hashicorp/vault-helm/blob/v0.13.0/templates/_helpers.tpl#L264

This causes a problem when I am attempting to experiment with vault-helm in a cluster where Linux and Windows machines reside and I want to deploy the vault server to Linux nodes only.

**To Reproduce**
1. Set `server.dev.enabled` to true, and define the `server.nodeSelector` setting
2. Install chart
3. Run `kubectl get pods -l app.kubernetes.io/name=vault` to get the pod name
4. Run `kubectl describe <pod_name>` and note the NodeSelector isn't set 

**Expected behavior**
`nodeSelector` to be used when configured even when dev is set to true

**Environment**
* Kubernetes version: 1.19
* vault-helm version: v0.13.0

Chart values:

```yaml
    server:
      enabled: true
      dev: 
        enabled: true
      nodeSelector: |
        kubernetes.io/os: linux
```
