### ISSUE TITLE
Vault agent can't authenticate using k8s 1.21

### ISSUE THREAD

**Issue by Marc-Pons** [hashicorp/vault-helm#562]
**Describe the bug**
Since I updated kind to 0.11, which by default uses k8s 1.21, my sidecar vault-agents can't authenticate with Vault showing the following error:
`[ERROR] auth.handler: error authenticating: error="context deadline exceeded" backoff=1s`

Using kind 0.11 and k8s 1.20, vault-agent authenticates correctly. The only fix I could find using k8s 1.21 is configuring the auth method specifying the issuer as follows:
```
vault write auth/kubernetes/config \
token_reviewer_jwt="$SA_JWT_TOKEN" \
kubernetes_host="$K8S_HOST" \
kubernetes_ca_cert="$SA_CA_CRT" \
issuer="https://kubernetes.default.svc.cluster.local"
```

Disabling the issuer validation with `disable_iss_validation=true` also works. I think the issue may be related to the following change introduced on k8s 1.21:
`The ServiceAccountIssuerDiscovery feature has graduated to GA, and is unconditionally enabled.`

**To Reproduce**
1. Install vault helm chart 0.13 in a kind 0.11 cluster using k8s 1.21
2. Configure an auth method as documented here: https://www.vaultproject.io/docs/auth/kubernetes.
2.1 Enable auth method: `vault auth enable kubernetes`
2.2 Configure the auth endpoint:
```
vault write auth/kubernetes/config \
    token_reviewer_jwt="<your reviewer service account JWT>" \
    kubernetes_host=https://192.168.99.100:<your TCP port or blank for 443> \
    kubernetes_ca_cert=@ca.crt
```
2.3 Create a named role:
```
vault write auth/kubernetes/role/demo \
    bound_service_account_names=vault-auth \
    bound_service_account_namespaces=default \
    policies=default \
    ttl=1h
```
2.4 Configure Kubernetes creeating a ClusterRoleBinding:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
```
3. Deploy a pod with vault-agent as sidecar using the configured auth method.

4. Check logs of vault-agent. You should see a periodic log that looks like:
`[ERROR] auth.handler: error authenticating: error="context deadline exceeded" backoff=1s`

**Expected behavior**
The documented steps to configure the auth method (https://www.vaultproject.io/docs/auth/kubernetes) should be working despite I am using k8s 1.21.

**Environment**
* Kubernetes version: 
  * Kind 0.11 with k8s 1.21
* vault-helm version:
  * Vault Helm Chart 0.13

Chart values:

```yaml
USER-SUPPLIED VALUES:
server:
  extraLabels:
    vault-server: "true"
  ha:
    config: "ui = true\n\nlistener \"tcp\" {\n  tls_disable = 1\n  address = \"[::]:8200\"\n
      \ cluster_address = \"[::]:8201\"\n}\n\nstorage \"consul\" {\n  path = \"vault/\"
      \ \n  address = \"consul-consul-server:8500\"\n}\n\nservice_registration \"kubernetes\"
      {}\n"
    enabled: true
    replicas: 2
```
