### ISSUE TITLE
injector.failurePolicy = "Fail" prevents the injector from starting if there is no namespaceSelector

### ISSUE THREAD

**Issue by dpp23** [hashicorp/vault-helm#609]
**Describe the bug**
If one sets `injector.failurePolicy = "Fail"` installing the helm chart succeeds, however if for some catastrophic failure all injector replicas go down, the deployment is stuck as it cannot start new pods as they are blocked.

I've worked around this by setting a `namespaceSelector` that ensures that the namespace the chart is installed in is excluded

Separately, the documentation here is incorrect - https://www.vaultproject.io/docs/platform/k8s/injector/installation#namespace-selector as it states that if you don't set `namespaceSelector` it will exclude `kube-system` and `kube-public` which isn't true.

**To Reproduce**
1. Install chart with `injector.failurePolicy = "Fail"`
2. `kubectl scale deployment vault-agent-injector --replicas=0`
3. `kubectl scale deployment vault-agent-injector --replicas=2`
4. Observe that the deployment with stuck now with 0 pods

**Expected behavior**
I am not sure if there is a good way to exclude the injector from its own webhook, but at least the documentation should state it clearly that one will need to exclude it themselves.

**Environment**
* Kubernetes version: 1.19
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS 
* vault-helm version: 0.15.0

Chart values:

```yaml
injector:
  agentImage:
    tag: 1.5.4
  failurePolicy: Fail
  image:
    tag: 0.12.0
  replicas: 2
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi

```

**Comment by Colbize** [comment]
Just hit this.

**Comment by Colbize** [comment]
We scale our EKS worker nodes down at night via asg to save on costs. On scale up sometimes the `vault-agent-injector` was too slow to boot causing multiple pods to go into crashbackloop as documented in this [https://github.com/hashicorp/vault-helm/issues/399](https://github.com/hashicorp/vault-helm/issues/399).

`failurePolicy: Fail` without selector was disastrous, preventing all pods from starting.

Ended up going with in our vault-helm config:
```
injector:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["vault","kube-system","kube-public","kube-node-lease"]
```
