### ISSUE TITLE
Add support for templateConfig.staticSecretRenderInterval

### ISSUE THREAD

**Issue by visomar** [hashicorp/vault-helm#611]
**Description of the problem**
After the release of Vault 1.8.0, it's been added the possibility to control the render/refresh time for secrets done by the vault-agent:
https://www.vaultproject.io/docs/agent/template-config#static_secret_render_interval
https://www.vaultproject.io/docs/release-notes/1.8.0

Nevertheless, there's no way to introduce that value directly through the attribute `injector.agentDefaults`, and you have to use a different approach, by introducing an environment variable named `AGENT_INJECT_TEMPLATE_STATIC_SECRET_RENDER_INTERVAL`.

**Description of the solution**
A way to directly introduce that value as in the example:
```
injector:
  agentDefaults:
    templateConfig:
      staticSecretRenderInterval: "30s"
```
