### ISSUE TITLE
Agent injector pod cannot be updated if hostnetwork=true due to default strategy rollingupdate

### ISSUE THREAD

**Issue by marianobilli** [hashicorp/vault-helm#615]
**Describe the bug**
When using `EKS` and an alternative `network plugin such as Calico` it is necessary to set `hostNetwork: true` to allow the EKS control plane to communicate with the vault-agent-injector pod. 
The negative side effect is that the port of the pod i.e 8080 is binded to the network interface of the node.
So when trying to recreate the pod via helm due to config update, given the default strategy is `RollingUpdate` a new pod tries to be created before killing the previous, and `pod update fails` because it cannot bind to the 8080 port on the node as it is already taken by the previous pod.

**To Reproduce**
1. Install EKS
2. Remove CNI plugin
3. Install Calico
4. Install vault agent injector via helm chart 
5. confirm vault agent injector pod has started
6. update values.yaml and set logLevel to `debug` 
7. Pod will be attempted to recreate and will fail because it can bind the port 

**Expected behavior**
In this case everything behaves as expected, but the problem here is that the chart does not give the possibility to `change the default strategy`

**Environment**
* Kubernetes version: 1.21
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
  * Other configuration options or runtime services (istio, etc.): Calico network plugin
* vault-helm version: 0.17.0

Chart values:
``` yaml
    injector:
      logLevel: info
      enabled: true
      port: 8081
      hostNetwork: true
      externalVaultAddr: "https://any-address/"
      authPath: "kubernetes"
    server:
      enabled: false
```

**Proposed Solution**
Update [injector-deployment.yaml](https://github.com/hashicorp/vault-helm/blob/master/templates/injector-deployment.yaml) template and allow to set strategy type. That way we can change default `RollingUpdate` to `Recreate`

``` yaml
spec:
  replicas: {{ .Values.injector.replicas }}
## Proposed Addition ###
  strategy:
    type: {{ .Values.injector.strategy.type }}
########################
```

I can create the pull request if you agree to the change
