### ISSUE TITLE
Ingress doesn't work with networking.k8s.io/v1 - no pathType set

### ISSUE THREAD

**Issue by tim-sendible** [hashicorp/vault-helm#633]
**Describe the bug**
The helm chart will not allow the user to correctly use a networking.k8s.io/v1 ingress as there is no option to set the PathType on the ingress. Kubernetes validation will deny the user.

**To Reproduce**
1. Install chart, enabling server.ingress. Add an ingressClassName and appropriate  additional ingress changes.
2. Kubernetes will prevent the ingress from installing:

```
Ingress.extensions "vault" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified
```

**Expected behavior**
I should be able to use a networking v1 ingress with the Vault Helm chart.

**Environment**
* Kubernetes version: 1.21
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): EKS
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version: 0.17.0

Chart values:

```yaml
server:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    activeService: true
    hosts:
      - host: vault.madeupdomain.biz

```

**Additional context**
