### ISSUE TITLE
Vault using OpenShift CA signer (Service CA Operator) : retry_join failed to retry join raft cluster 

### ISSUE THREAD

**Issue by erlisb** [hashicorp/vault-helm#645]
**Describe the bug**

We are planning to use Vault for production, on OpenShift 4.7 and one the requirements for a production-ready Cluster is TLS end-to-end termination. For that we are planning to use the Openshift CA Signer (Service CA Operator) to generate SSL certificates. 
What OpenShift Service CA Operator basically does, is that it issues a signed serving certificate/key pair to services annotated with 'service.beta.openshift.io/serving-cert-secret-name' via a secret.

From our tests, it looks like the certificates (within the secret) seem to be created correctly, but when the cluster is initialized and cluster nodes try to join the cluster, the following error is produced : 

> 2021-11-09T10:21:32.834Z [ERROR] core: failed to retry join raft cluster: retry=2s
> 2021-11-09T10:21:34.835Z [INFO]  core: security barrier not initialized
> 2021-11-09T10:21:34.835Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault-0.vault-internal:8200
> 2021-11-09T10:21:34.839Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://vault-0.vault-internal:8200/v1/sys/storage/raft/bootstrap/challenge": x509: certificate is valid for vault.management-dev.svc, vault.management-dev.svc.cluster.local, not vault-0.vault-internal"
> 
> 2021-11-09T10:21:34.839Z [INFO]  core: security barrier not initialized
> 2021-11-09T10:21:34.839Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault-1.vault-internal:8200
> 2021-11-09T10:21:34.842Z [INFO]  http: TLS handshake error from 10.129.4.186:57386: remote error: tls: bad certificate
> 2021-11-09T10:21:34.842Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://vault-1.vault-internal:8200/v1/sys/storage/raft/bootstrap/challenge": x509: certificate is valid for vault.management-dev.svc, vault.management-dev.svc.cluster.local, not vault-1.vault-internal"

**To Reproduce**
1. Install chart

> helm upgrade --install  vault -n management-dev -f values.openshift.yaml .

2. Run vault command

> bash-4.4$ vault operator init --tls-skip-verify
> bash-4.4$ vault status --tls-skip-verify
> Key                      Value
> ---                      -----
> Recovery Seal Type       shamir
> Initialized              true
> Sealed                   false

3. See error (vault logs, etc.)
> 2021-11-09T10:21:32.834Z [ERROR] core: failed to retry join raft cluster: retry=2s
> 2021-11-09T10:21:34.835Z [INFO]  core: security barrier not initialized
> 2021-11-09T10:21:34.835Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault-0.vault-internal:8200
> 2021-11-09T10:21:34.839Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://vault-0.vault-internal:8200/v1/sys/storage/raft/bootstrap/challenge": x509: certificate is valid for vault.management-dev.svc, vault.management-dev.svc.cluster.local, not vault-0.vault-internal"
> 
> 2021-11-09T10:21:34.839Z [INFO]  core: security barrier not initialized
> 2021-11-09T10:21:34.839Z [INFO]  core: attempting to join possible raft leader node: leader_addr=https://vault-1.vault-internal:8200
> 2021-11-09T10:21:34.842Z [INFO]  http: TLS handshake error from 10.129.4.186:57386: remote error: tls: bad certificate
> 2021-11-09T10:21:34.842Z [WARN]  core: join attempt failed: error="error during raft bootstrap init call: Put "https://vault-1.vault-internal:8200/v1/sys/storage/raft/bootstrap/challenge": x509: certificate is valid for vault.management-dev.svc, vault.management-dev.svc.cluster.local, not vault-1.vault-internal"

The following helm templates have been modified as shown below : 

server-service.yaml : 

> {{- if .Values.global.openshift }}
>     service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-vault-cert-active
> {{- end }}
>     service.beta.kubernetes.io/tolerate-unready-endpoints: "true"

server-route.yaml : 

>   tls:
>     termination: edge
>     insecureEdgeTerminationPolicy: Redirect

Certificates has been generated as shown below : 

> bash-4.4$ ls /var/run/secrets/kubernetes.io/certs/
> tls.crt  tls.key

**Expected behavior**
Vault cluster is initialized and nodes are joined into the cluster. 
Expected result : 

> bash-4.4$ vault operator raft list-peers --tls-skip-verify
> Node                                    Address                         State     Voter
> ----                                    -------                                -----     -----
> XXXXXXXXXXXXXXX    vault-0.vault-internal:8201    leader    true
> XXXXXXXXXXXXXXX    vault-1.vault-internal:8201    follower true

**Environment**
* Kubernetes version: 
  * Distribution : OpenShift 4.7

* vault-helm version: 0.17.1
* vault version : 1.8.4

Chart values:

```yaml
global:
  enabled: true
  # TLS for end-to-end encrypted transport
  tlsDisable: false
  # If deploying to OpenShift
  openshift: true
server:
  ha:
    enabled: true
    replicas: 2

    apiAddr: null
    raft:
      enabled: true
      setNodeId: false
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
          tls_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
          tls_client_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            leader_client_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
            leader_client_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file  = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            leader_client_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
            leader_client_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
          }
        }

```

Any support/suggestion would be appreciated.
Many thanks.

**Comment by eye0fra** [comment]
Hi @erlisb ,
You do not need to edit the chart template to leverage the OpenShift annotations. Here a snippet of the values.yaml:

```
global:
  tlsDisable: false
  openshift: true

ui:
  enabled: true

server:
  extraEnvironmentVars:
    VAULT_CAPATH: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
    VAULT_ADDR: vault-internal.hashicorp.svc.cluster.local:8200

  route:
    enabled: true
    host: vault.apps.openlab.red

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-secret/tls.crt"
        tls_key_file = "/vault/userconfig/vault-secret/tls.key"
      }
      storage "file" {
        path = "/vault/data"
      }
  ha:
    enabled: false

  extraVolumes:
  - type: secret
    name: vault-secret

  service:
    enabled: true
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: vault-secret
 ```
