### ISSUE TITLE
Error: UPGRADE FAILED: cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by venu1428** [hashicorp/vault-helm#658]
**Describe the bug**

We have tried to upgrade the vault from version 1.6.2 to 1.8.3 with helm vault chart versions of 0.9.1 to 0.16.1 with reference of https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes with helm upgrade command.
But we are getting below error while execute upgrade command.

Error: UPGRADE FAILED: cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

**To Reproduce**

1. Searched and added of helm repo 0.16.1 which is having vault version 1.8.3.
2. Changed vault tag versions and k8s tag versions in values.yml file as per reference docs.
2. Executed helm upgrade command 
   helm upgrade vault hashicorp/vault --version 0.16.1 \
   --set='server.image.repository=vault' \    --set='server.image.tag=1.8.3' \
3. See error (vault logs, etc.)
    Error: UPGRADE FAILED: cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to   statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Expected behavior**

Vault should upgrade to 1.8.3 in HA env by deleting follower nodes first and then leader node after that.

**Environment**

  Kubernetes version: 1.20.3
  vault-helm version: 0.16.1
  helm version: v3.3.4

Chart values:
We have put the same values like before only changes tag versions according to upgrade documentation.

**Comment by venu1428** [comment]
Thanks for the support 

We are able to upgrade by passing

helm upgrade vault hashicorp/vault -f  values.yml --version 0.16.1
--set='server.image.repository=vault' \ --set='server.image.tag=1.8.3' \

Hence closing the case

**Comment by boldandbusted** [comment]
Hmm... I just got this issue. @venu1428 - what is different in your values.yml file above? Thanks.

**Comment by Ramesh7** [comment]
Hi @boldandbusted @venu1428,
Today I got a similar issue when trying to enable HA but when I disable HA it works fine. Not sure what I am missing here, can you please help me out?
Here is my values.yml : 
```
injector:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
      - host: vault-dev-na10001-eks.io.coupadev.com
    annotations:
      kubernetes.io/ingress.class: nginx
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    tls: 
      - secretName: ingress-tls
        hosts:
          - vault-dev-na10001-eks.io.coupadev.com
  extraVolumes:
    - type: configMap
      name: mysql-ca-cert-config
      path: /vault/userconfig
    - type: secret
      name: coupa-secret-store-storage-secrets
  extraArgs: '-config=/vault/userconfig/vault-storage-config/config.hcl'
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true
  image:
    tag: "1.8.2"
    repository: "vault"
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = false

      service_registration "kubernetes" {}
```

Have tried command line passing the required repository and tag but that even didn't work.
```
	 cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
client.go:501: [debug] Looks like there are no changes for Ingress "vault"
upgrade.go:420: [debug] warning: Upgrade "vault" failed: cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Error: UPGRADE FAILED: cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
helm.go:88: [debug] cannot patch "vault" with kind StatefulSet: StatefulSet.apps "vault" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
helm.sh/helm/v3/pkg/kube.(*Client).Update
```

Here is the version setup  : 
Helm Chart Version: 0.19.0
Helm Version: v3.7.0
Kubernetes Version: v1.20.7-eks-135321
