### ISSUE TITLE
Network policy 'policyTypes' not explicit

### ISSUE THREAD

**Issue by SlyngDK** [hashicorp/vault-helm#662]
**Describe the bug**
If your adding egress after network policies is enabled, the egress is not handled by kubernetes.

**To Reproduce**
1. Install chart with network policies without egress rules
```
...
server:
  networkPolicy:
    enabled: true
```
2. Update chart with network policies and now with egress rules
```
...
server:
  networkPolicy:
    enabled: true
    egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: vault
      ports:
      - port: 8200
        protocol: TCP
      - port: 8201
        protocol: TCP
```

**Expected behavior**

I expected kubernetes to use the egress rule, but when `policyTypes` don't contains `Egress`, it ignores egress in that network policy.

I would expected to `policyTypes` to contain `Egress` and `Ingress`, after deployed.

**Environment**
* Kubernetes version: 1.21.6
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): Rancher RKE
  * Other configuration options or runtime services (istio, etc.): Calico
* vault-helm version: 0.18.0
