### ISSUE TITLE
service annotations applied to both vault and vault-internal services

### ISSUE THREAD

**Issue by raffaelespazzoli** [hashicorp/vault-helm#674]
**Describe the bug**
the annotations in the service section are applied to both the `vault` and the `vault-internal` services and there is not way to distinguish between the two.
When deploying to OpenShift and the annotation is used to request a certificate, this causes a race condition because two services are trying to modify the same secret (containing the certificate)

**To Reproduce**
1. Install chart

with these options:

```
global:
  openshift: true
  tlsDisable: false
  
  ...
server:
  service: 
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: vault-server-tls

```

try to connect to the vault instance via the vault service. 50% of the times the connection will fails because the cert cannot be validated.

Suggested solution: allow for a way to attribute annotations to individual services.
Also when did this change? As a workaround one could use the old version in which this used to work.
