### ISSUE TITLE
injector.webhook.objectSelector and injector.webhook.namespaceSelector not working

### ISSUE THREAD

**Issue by natilik-mikeguy** [hashicorp/vault-helm#718]
For questions, the best place to get answers is on our [discussion forum](https://discuss.hashicorp.com/c/vault), as they will get more visibility from experienced users than the issue tracker.

Please note: We take Vault's security and our users' trust very seriously. If you believe you have found a security issue in Vault Helm, _please responsibly disclose_ by contacting us at [security@hashicorp.com](mailto:security@hashicorp.com).

**Describe the bug**
When using the newer injector.webhook.objectSelector and injector.webhook.namespaceSelector values, the values are not populated in the generated yaml.

**To Reproduce**
Example snippet of the relevant override values shown below:

### Snippet of vault-overrides.yaml
```yaml
injector:
  enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.15.0"
    pullPolicy: IfNotPresent
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.10.0"
  webhook:
    objectSelector:
      matchLabels:
        vault-sidecar-injector: enabled
```

### Dry run output
```yaml
# Source: vault/templates/injector-mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: vault.hashicorp.com
    sideEffects: None
    admissionReviewVersions:
    - "v1beta1"
    - "v1"
    clientConfig:
      service:
        name: vault-agent-injector-svc
        namespace: vault
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore

```

**Expected behavior**
The objectorSelector and namespaceSelector values should be populated.

The legacy values (injector.objectSelector and injector.namespaceSelector) still appear to work fine...

### Snippet of vault-overrides.yaml
```yaml
injector:
  enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.15.0"
    pullPolicy: IfNotPresent
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.10.0"
  # Bug preventing usage
  # webhook:
  #   objectSelector:
  #     matchLabels:
  #       vault-sidecar-injector: enabled
  objectSelector:
    matchLabels:
      vault-sidecar-injector: enabled
```

### Dry-run output
```yaml
# Source: vault/templates/injector-mutating-webhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
webhooks:
  - name: vault.hashicorp.com
    sideEffects: None
    admissionReviewVersions:
    - "v1beta1"
    - "v1"
    clientConfig:
      service:
        name: vault-agent-injector-svc
        namespace: vault
        path: "/mutate"
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchLabels:
        vault-sidecar-injector: enabled

    failurePolicy: Ignore

```

**Environment**
* Kubernetes version: 1.21.4
  * On-prem Kubernetes
* vault-helm version: 0.19.0
