### ISSUE TITLE
Could not chown /vault/config (may not have appropriate permissions)

### ISSUE THREAD

**Issue by laurentiuspurba** [hashicorp/vault-helm#72]
Running into the following issue, **could not chown /vault/config**. 
```
chown: /vault/config/extraconfig-from-values.hcl: Read-only file system
chown: /vault/config/..data: Read-only file system
chown: /vault/config/..2019_10_02_19_14_10.869393029/extraconfig-from-values.hcl: Read-only file system
chown: /vault/config/..2019_10_02_19_14_10.869393029: Read-only file system
chown: /vault/config/..2019_10_02_19_14_10.869393029: Read-only file system
chown: /vault/config: Read-only file system
chown: /vault/config: Read-only file system
Could not chown /vault/config (may not have appropriate permissions)
==> Vault server configuration:

      GCP KMS Crypto Key: xxx-xxx-xxx-xxx
        GCP KMS Key Ring: xxx-xxx-xxx
         GCP KMS Project: xxx-xxx-xxx
          GCP KMS Region: us
               Seal Type: gcpckms
             Api Address: http://10.88.14.191:8200
                     Cgo: disabled
         Cluster Address: https://10.88.14.191:8201
              Listener 1: tcp (addr: "[::]:8200", cluster address: "[::]:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: true
                 Storage: gcs (HA disabled)
                 Version: Vault v1.0.3
             Version Sha: 85909e3373aa743c34a6a0ab59131f61fd9e8e43

2019-10-02T19:14:15.412Z [WARN]  core: entering seal migration mode; Vault will not automatically unseal even if using an autoseal
2019-10-02T19:14:15.413Z [WARN]  failed to unseal core: error="cannot auto-unseal during seal migration"
```
with `values.yaml`:
```
global:
  enabled: true
  image: "vault:1.2.2"

server:
  extraEnvironmentVars:
    GOOGLE_REGION: us
    GOOGLE_PROJECT: xxx-xxx-xxx
    GOOGLE_CREDENTIALS: /vault/userconfig/xxx-xxx-xxx/credentials.json
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/xxx-xxx-xxx/credentials.json

  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 250m

  extraVolumes:
    - type: "secret"
      name: "xxx-xxx-xxx"
      load: false

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "vault.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

  annotations: |
    prometheus.io/scrape: "true"
    prometheus.io/path: "/v1/sys/metrics"
    prometheus.io/port: "8200"

  service:
    enabled: true

  ha:
    enabled: true
    replicas: 3

    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "gcs" {
        bucket        = "xxx-xxx-xxx"
      }

      seal "gcpckms" {
         project     = "xxx-xxx-xxx"
         region      = "us"
         key_ring    = "xxx-xxx-xxx"
         crypto_key  = "xxx-xxx-crypto-key"
      }

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 80
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
```
The vault status is as follows:
```
Key                      Value
---                      -----
Recovery Seal Type       shamir
Initialized              true
Sealed                   true
Total Recovery Shares    11
Threshold                2
Unseal Progress          0/2
Unseal Nonce             n/a
Version                  1.0.3
HA Enabled               false
command terminated with exit code 2
```

The pods were created, and looking at the log file see the following
```
2019-10-04T14:08:23.440Z [ERROR] core: failed to create audit entry: path=file/ error="sanity check failed; unable to open "/var/log/vault/audit.log" for writing: mkdir /var/log/vault: permission denied"
```

I issued command `vault audit enable file file_path=/vault/audit/vault_audit.log`, but it didn't work. I issued command `vault operator unseal -migrate`, it didn't work either after entering the recovery key(s).

If I manually created  a folder `mkdir /var/log/vault` and change ownership to vault `chown vault:vault /var/log/vault`, then the vault cluster will be unsealed automatically.

Am I missing something?
