### ISSUE TITLE
The current affinity rules doesn't match pods labels

### ISSUE THREAD

**Issue by larsha** [hashicorp/vault-helm#73]
Hi,

The current podAntiAffinity labels in `values.yaml` doesn't match pods labels. The result is that pods can be scheduled to same node. I can easily add a PR for this if you would like.

## values.yaml
```yaml
affinity: |
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: {{ template "vault.name" . }}
            release: "{{ .Release.Name }}"
            component: server
        topologyKey: kubernetes.io/hostname
```

## server-statefulset.yaml
```yaml
selector:
  matchLabels:
    helm.sh/chart: {{ template "vault.chart" . }}
    app.kubernetes.io/name: {{ template "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: server
```
