### ISSUE TITLE
Vault Agent Injector Annotations are not creating : External EKS

### ISSUE THREAD

**Issue by jgourmelen** [hashicorp/vault-helm#731]
**Describe the bug**

I have 2 AWS EKS Cluster.

ClusterA : Full Vault installation (Helm)
ClusterB  : ExternalAddr (to ClusterA) configuration for vault injector (Helm)

Injector is OK inside CLusterA.

But, inside ClusterB injector do nothing : 
My pod is always with status (1/1) and not (2/2)

I didn't find any interesting log inside vault.
I don't know what can i do.

```
 NAME                                    READY   STATUS    RESTARTS   AGE
 app-68b467cb54-khfnv                    1/1     Running   0          24h
 devwebapp                               1/1     Running   0          17h
 devwebapp-with-annotations              1/1     Running   0          14m
 vault-agent-injector-554c56bb59-tl99l   1/1     Running   0          15h
 
```
I have used this tutorial : https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault

**Environment**
* Kubernetes version: 1.22
  * AWS EKS 1.22
* vault-helm version: latest

**Comment by tvoran** [comment]
Hi @jgourmelen, the next place to look is in the logs of the injector pod, vault-agent-injector-554c56bb59-tl99l. If you can share the values used to deploy the chart in ClusterB, and the annotations used in the app, that would be helpful.

**Comment by dcshiman** [comment]
same issue here, the vault injector does not have any informative logs

```
2022-06-03T15:16:05.135Z [INFO]  handler.auto-tls: Generated CA
2022-06-03T15:16:05.140Z [INFO]  handler: Starting handler..
Listening on ":8080"...
2022-06-03T15:16:05.235Z [INFO]  handler.certwatcher: Updated certificate bundle received. Updating certs...
2022-06-03T15:16:05.248Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:16:05.255Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:16:05.256Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:16:05.256Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:16:05.256Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:16:05.256Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:31.275Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:31.686Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:35.804Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:36.310Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:43.307Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
2022-06-03T15:33:43.891Z [INFO]  handler.certwatcher: Webhooks changed. Updating certs...
```

Log level = debug
Infrastructure = AWS EKS
K8S Version = 1.22
Vault Agent Image = hashicorp/vault-k8s:0.16.1
Vault Server Image = hashicorp/vault:1.10.3

I was suspecting it is an issue with `MutatingWebhookConfiguration` for api version `admissionregistration.k8s.io/v1` so changed `Match Policy:    Equivalent` with no luck. Here is the results for my config 
`kubectl describe mutatingwebhookconfigurations hashi-vault-ha-agent-injector-cfg`

```
Name:         hashi-vault-ha-agent-injector-cfg
Namespace:
Labels:       app.kubernetes.io/instance=hashi-vault-ha
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault-agent-injector
Annotations:  meta.helm.sh/release-name: hashi-vault-ha
              meta.helm.sh/release-namespace: ci-tools
API Version:  admissionregistration.k8s.io/v1
Kind:         MutatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2020-11-16T04:39:41Z
  Generation:          13455
  Resource Version:    277197809
  UID:                 cc6eb59c-c18b-489d-b85b-d39a7b0d16c4
Webhooks:
  Admission Review Versions:
    v1
    v1beta1
  Client Config:
    Ca Bundle:  < hidden >
    Service:
      Name:        hashi-vault-ha-agent-injector-svc
      Namespace:   ci-tools
      Path:        /mutate
      Port:        443
  Failure Policy:  Ignore
  Match Policy:    Equivalent
  Name:            vault.hashicorp.com
  Namespace Selector:
  Object Selector:
    Match Expressions:
      Key:       app.kubernetes.io/name
      Operator:  NotIn
      Values:
        vault-agent-injector
  Reinvocation Policy:  Never
  Rules:
    API Groups:

    API Versions:
      v1
    Operations:
      CREATE
      UPDATE
    Resources:
      pods
    Scope:          *
  Side Effects:     None
  Timeout Seconds:  30
Events:             <none>
```

The agent seems up and reachable from pods

**Comment by tvoran** [comment]
Hi folks, another place to look for clues is the kube-apiserver logs, which should report failures to call the mutating webhook service.

@dcshiman The vault injector shouldn't typically be logging `Webhooks changed. Updating certs...` that frequently, so I wonder if you perhaps scaled the injector deployment outside the helm chart? If two replicas of the injector are running and not coordinating, they'll both constantly update the webhook config like that. Make sure you set the number of replicas for injector only by setting `injector.replicas` in the chart.

**Comment by dizeee** [comment]
My API server log has this:
```
E0707 18:28:11.927844 10 webhook.go:155] Failed to make webhook authenticator request: unknown
E0707 18:28:11.927911 10 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, serviceaccounts \"vault-agent-injector\" not found, unknown]"
```
Injectors seem fine, there's a few `handler.certwatcher: Webhooks changed. Updating certs...` lines in logs when they start, but then one of them gets elected as leader and all get quiet.

**Comment by dizeee** [comment]
Also, after some attempts:
```
I0707 21:31:50.421082 10 trace.go:205] Trace[1435112639]: "Call mutating webhook" configuration:vault-agent-injector-cfg,webhook:vault.hashicorp.com,resource:/v1, Resource=pods,subresource:,operation:CREATE,UID:c8723581-6f00-488c-96d3-7e71d2e51ecc (07-Jul-2022 21:31:20.419) (total time: 30001ms): Trace[1435112639]: [30.001091767s] [30.001091767s] END
W0707 21:31:50.421129 10 dispatcher.go:176] Failed calling webhook, failing open vault.hashicorp.com: failed calling webhook "vault.hashicorp.com": failed to call webhook: Post "https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0707 21:31:50.421162 10 dispatcher.go:180] failed calling webhook "vault.hashicorp.com": failed to call webhook: Post "https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by kholisrag** [comment]
any other way rather then looking at api server log? @tvoran 
I faced same issue, dunno whats wrong, and vault agent injector can't inject to a pod when annotations already there?

EKS 1.23,

`values.yaml`

```yaml
global:
  enabled: true
  tlsDisable: false
  externalVaultAddr: "${VAULT_ADDR}"
injector:
  enabled: true
  replicas: 1
  leaderElector:
    enabled: true
  metrics:
    enabled: true
  externalVaultAddr: "${VAULT_ADDR}"
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  agentImage:
    repository: "hashicorp/vault"
    tag: "1.11.3"
  agentDefaults:
    cpuLimit: "100m"
    cpuRequest: "10m"
    memLimit: "100Mi"
    memRequest: "10Mi"
  authPath: "auth/kubernetes"
  nodeSelector:
    kubernetes.io/os: linux
    nodegroup-name: critical-addons-tools-ng
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
server:
  enabled: false
ui:
  enabled: false
csi:
  enabled: false
```

**Comment by tvoran** [comment]
@kholisrag Glad you got it working! The communication requirements for vault-k8s are outlined [here](https://www.vaultproject.io/docs/platform/k8s/injector/examples#connectivity) as well.

**Comment by Pursu1tOfHapp1ness** [comment]
Guys, good morning.

Have almost the same issue that described previously, but with some additional requirements:
- I need to put `vault-injector` and `vault` to separate EKS managed nodegroup with taint and label.
- My current workload is running on default EKS managed nodegroup without any taints or labels.

So, I created custom helm values config file with such configuration:
```yaml
injector:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}-agent-injector
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: webhook
          topologyKey: kubernetes.io/hostname
     nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "KEY"
            operator: In
            values:
            - "VALUE" 
server:
  ha:
    enabled: true
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "KEY"
            operator: In
            values:
            - "VALUE"
  tolerations: |
    - key: "KEY"
      operator: "Equal"
      value: "VALUE"
      effect: "NoSchedule"
ui:
  enabled: true
```

After applying this configuration, I saw that `vault-injector` was placed on the needed EKS Nodegroup. Then I was trying to check, that `vault-injector` insert needed credentials into the pod of my application, lets called it `app1`. So, the result is that `vault-injector` just does not create any init container for inserting/putting creds. But when I remove `nodeAffinity` rule and my `vault-injector` deployment was placed by scheduler to the same Nodegroup as current workload - everything continued working well without any errors.
Due to using `terraform-aws-modules/eks` for deploying EKS cluster with `node_security_group_enable_recommended_rules = true` that opens ports in Node-2-Node connections from `1024-65536`, I am wondering, what can cause this issue? I think mutation webhook just didn't start and that cause this behavior.
