### ISSUE TITLE
Plugin folder key ignored inside configuration when using ha raft storage.

### ISSUE THREAD

**Issue by blegros-exte** [hashicorp/vault-helm#734]
I use the helm chart to automatically provision the Vault servers inside my Kubernetes cluster. I also need a specific plugin to be available in the container, therefore I specify the directory path inside the server.ha.config key.
However, the server.ha.config. plugin_directory key disappears when applied inside the ConfigMap extraconfig-from-values.hcl file, therefore I need to add this configuration afterwards.

Here is the config file:
```yaml
global:
  tlsDisable: true
  imagePullSecrets:
    - name: 'dockerhub'
server:
  auditStorage:
    enabled: false
  resources:
    requests:
      cpu: '500m'
      memory: '1Gi'
    limits:
      cpu: '500m'
      memory: '1Gi'
  standalone:
    enabled: false
  ha:
    enabled: true
    config: |
      disable_mlock = true
      service_registration "kubernetes" {}
      plugin_directory = "/vault/plugins"
      
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      
      storage "raft" {
        path = "/vault/data"
      }
    raft:
      enabled: true
    replicas: 3
ui:
  enabled: true
```

Here is the content of the ConfigMap:
```hcl
{
  "disable_mlock": true,
  "listener": {
    "tcp": {
      "address": "[::]:8200",
      "cluster_address": "[::]:8201"
    }
  },
  "raft": {
    "enabled": true
  }
}
```

Is there a way to workaround this problem ?
Thanks you.
