### ISSUE TITLE
Custom values are not deployed once global parameter is set to false

### ISSUE THREAD

**Issue by lugtusonny** [hashicorp/vault-helm#747]
**Describe the bug**
Deployed vault via argocd but the custom values like HA enabled is not taking effect.

Take note that I have read other issues related to this but issue still occured:
https://github.com/hashicorp/vault-helm/pull/727
https://github.com/hashicorp/vault-helm/issues/714

**To Reproduce**
1. Install chart via argocd using below parameters in values.yaml:
```
global:
  enabled: false
  tlsDisable: true
  psp:
    enable: true
    annotations: |
      seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
      seccomp.security.alpha.kubernetes.io/defaultProfileName:  runtime/default
injector:
  enabled: false
server:
  enabled: true
  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: "nfs-ha"
    accessMode: ReadWriteOnce
    annotations: |
      nfs.io/storage-path-suffix : "-db"
  ha:
    enabled: true
```

2. No statefulset has been created. 

**Expected behavior**
Vault is deployed as HA setup.

**Environment**
* Kubernetes version: v1.21.8
* vault-helm version: All

Chart values:

```yaml
apiVersion: v2
name: vault
version: 0.20.0
appVersion: 1.10.3
kubeVersion: ">= 1.16.0-0"
description: Official HashiCorp Vault Chart
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
keywords: ["vault", "security", "encryption", "secrets", "management", "automation", "infrastructure"]
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-helm
  - https://github.com/hashicorp/vault-k8s
  - https://github.com/hashicorp/vault-csi-provider

dependencies:
- name: vault
  version: 0.20.0
  repository: https://helm.releases.hashicorp.com

```

**Additional context**
