### ISSUE TITLE
auditStorage to support a remote logging collector

### ISSUE THREAD

**Issue by AlyRagab** [hashicorp/vault-helm#755]
It is clear on the documentation that the Audit Device type `file` is not rotated so i suggest : 

1- Adding audit file rotation feature or if it is available then can we document how to ?
2- Allow sending the audit logs to any other log collector like `Datadog` or any other by exporting the audit logs as STDOUT

**Comment by AlyRagab** [comment]
I think this feature is really needed since there is no any sensitive data is getting logged ( as it is hashed ) as per the official documentation

**Comment by AlyRagab** [comment]
I have implemented a solution around this problem, it is here https://github.com/AlyRagab/Vault-Audit-Logging

**Comment by hortonew** [comment]
I did something similar @AlyRagab .  I'm going to use a fluentd sidecar, but as a test I'm doing:

```
helm install vault hashicorp/vault --version 0.25.0 --values values.yml

# Connect to pod in order to enable audit logging
kubectl exec -it vault-0 -- /bin/sh
vault audit enable file file_path=/vault_audit/audit.log

# you should be able to see all the logs from your log-reader container
```

```
# values.yml
global:
  enabled: true
server:
  affinity: ""
  updateStrategyType: RollingUpdate
  dev:
    enabled: true
  volumes:
    - name: logs
      emptyDir: {}
  volumeMounts:
    - name: logs
      mountPath: /vault_audit
  extraInitContainers:
  - name: init-log-file
    image: busybox:1.31
    command: ["touch", "/vault_audit/audit.log"]
    volumeMounts:
    - name: logs
      mountPath: /vault_audit
  extraContainers:
    - name: log-reader
      image: ubuntu:latest
      command: ["tail", "-f", "/vault_audit/audit.log"]
      volumeMounts:
        - name: logs
          mountPath: /vault_audit
```
