### ISSUE TITLE
csi.authPath Kubernetes settings missing for the vault provider csi

### ISSUE THREAD

**Issue by gauthierc** [hashicorp/vault-helm#760]
When adding kubernetes authentication in vault it is possible to specify in the values.yaml the variable injector.authPath allowing to define another path than auth/kubernetes. This is apparently not possible for csi.

Is it possible to extend the helm setting for csi?

**Comment by gauthierc** [comment]
My apologies for the inconvenience.
The path should be specified in the SecretProviderClass like this:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: db-password
    secretName: dbpass
    type: Opaque
  parameters:
    vaultAddress: "http://vault:8200"
    vaultKubernetesMountPath: rancher-desktop
    roleName: "database"
    objects: |
        - objectName: "db-password"
        secretPath: "kv/data/apps/webapp-sa/db-pass"
        secretKey: "password"
```
