### ISSUE TITLE
Add option to configure pod and container level securityContext

### ISSUE THREAD

**Issue by r0bj** [hashicorp/vault-helm#764]
**Is your feature request related to a problem? Please describe.**
It's becoming more common to restrict application namespaces with Pod Security Admission (https://kubernetes.io/docs/concepts/security/pod-security-admission/) especially with restricted Pod Security Standard (https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted).
Unfortunately currently there is no flexible option to configure `securityContext` for pods and containers (e.g. vault-agent-injector) via helm values.

**Describe the solution you'd like**
Add option to configure pod and container level `securityContext` via helm values. In order to be compliant with restricted Pod Security Standard, container's `securityContext` would need to look similar to:
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```
