### ISSUE TITLE
Global Enabled False and Server Enabled True does nothing 

### ISSUE THREAD

**Issue by EvertonSA** [hashicorp/vault-helm#765]
**Describe the bug**
installing server only is not possible even after recent changes on the global tag

**To Reproduce**
1. create empty helm project
2. add vault helm chart as dependency:
```
dependencies:
  - name: vault
    version: "0.20.1"
    repository: "https://helm.releases.hashicorp.com"
```
3. run `helm dependency build`
4 create dummy values.yaml file like bellow
5. Run `helm template vault -f .\values.yaml . > template.yaml`
6. template file will be empty

**Expected behavior**
server to be deployed with default configuration

**Environment**
* vault-helm version: 0.20.1

Chart values:

```yaml
global:
  enabled: false
injector:
  enabled: false
server:
  enabled: true
```

**Additional context**

**Comment by EvertonSA** [comment]
closing as values should be:
```
vault:
  global:
    enabled: false
  injector:
    enabled: false
  server:
    enabled: true
```
