### ISSUE TITLE
Switching `global.tlsDisable` to `false` causes readiness probe to fail

### ISSUE THREAD

**Issue by WoodyWoodsta** [hashicorp/vault-helm#766]
**Describe the bug**
Switching `global.tlsDisable` to `false` causes `Readiness probe failed: Error checking seal status: Get "https://127.0.0.1:8200/v1/sys/seal-status": http: server gave HTTP response to HTTPS client`.

**To Reproduce**
1. Install chart with default `global.tlsDisable` of `true` (which surprises me already 😁)
2. Upgrade release with new setting of `global.tlsDisable: false`, restart the Vault StatefulSet
3. Readiness probe fails with above error

**Expected behavior**
`global.tlsDisable` to be... global?

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.): Kubernetes
  * Other configuration options or runtime services (istio, etc.): N/A
* vault-helm version: 0.20.1

Chart values:

```yaml
vault:
  global:
    tlsDisable: false
  server:
    nodeSelector:
      ...
    dataStorage:
      storageClass: vault-pv-storage
    ingress:
 	  ...
  injector:
    enabled: true
```
