### ISSUE TITLE
auto-unseal returns denied for resource even with proper service account permissions

### ISSUE THREAD

**Issue by mprinvale** [hashicorp/vault-helm#77]
Running `helm install --name=vault --set='server.ha.enabled=true' .`
Results in
`Error parsing Seal configuration: failed to encrypt with GCP CKMS - ensure the key exists and the service account has at least roles/cloudkms.cryptoKeyEncrypterDecrypter permission: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied for resource 'projects/my-project/locations/us-east1/keyRings/vault-helm-unseal-kr-1/cryptoKeys/vault-key'.`

Confirmed service account is being used (via KMS API monitoring) and the service account has proper permissions (encrypt/decrypt/get, also tried granting service account full project owner permissions). 

consul-helm as backend
vault-helm-0.12

snippets from values.yaml (Tried both ways below, with GOOGLE_APPLICATION_CREDENTIALS, and without) - all other values.yaml default. 
``` 
extraEnvironmentVars:
    #GOOGLE_REGION: us-east1
    #GOOGLE_PROJECT: my-project
    #GOOGLE_CREDENTIALS: /vault/userconfig/my-project/my-project-1234.json
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/redacted/my-project-1234.json

  extraVolumes:
    - type: secret
      name: my-project
      load: false # if true, will add to `-config` to load by Vault
    #   path: null # default is `/vault/userconfig`


      seal "gcpckms" {
         credentials = "/vault/userconfig/my-project/my-project-1234.json"
         project     = "my-project"
         region      = "us-east1"
         key_ring    = "vault-helm-unseal-kr-1"
         crypto_key  = "vault-key"
      }
```

- Standard GKE cluster with workload identity enabled
- Node pool setup to use service-account

**Comment by jasonodonnell** [comment]
Hi @mprinvale,

I see the environment variables in your example have been commented out.  You tried using all of these environment variables at once?  

I'm not able to reproduce this on my end: Vault is auto unsealing using Google KMS from a GKE cluster using a service account with `Cloud KMS CryptoKey Encrypter/Decrypter` permissions.  One thought was, does the key already exist within the keyring?  If the key doesn't exist, it will require permissions to create it (KMS admin).

My deployment looks like this:

```yaml
global:
  enabled: true
  image: "vault:1.2.3"

server:
  extraEnvironmentVars:
    GOOGLE_REGION: us-east1
    GOOGLE_PROJECT: vault-helm-dev
    GOOGLE_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json

  extraVolumes:
    - type: "secret"
      name: "kms-creds"

  ha:
    enabled: true
    replicas: 3

    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      seal "gcpckms" {
        project     = "us-east1"
        region      = "vault-helm-dev"
        key_ring    = "vault-helm-test"
        crypto_key  = "vault-helm-us-east"
      }

      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
      }
```
