### ISSUE TITLE
`VAULT_CLUSTER_ADDR` not working when using FluxCD

### ISSUE THREAD

**Issue by justusbunsi** [hashicorp/vault-helm#780]
**Describe the bug**

Since #709, it's possible to override the `VAULT_CLUSTER_ADDR` environment variable by setting `.server.ha.clusterAddr` as value. This works fine when natively running `helm install` or `helm upgrade`.
I am using FluxCD to manage Helm releases in the cluster, where the actual Helm command is wrapped. I'm not fully sure at which step the environment variable is lost, but the created/updated StatefulSet in the cluster does not contain the `VAULT_CLUSTER_ADDR` environment variable anymore, causing Vault pods to restart in a infinity loop.

**To Reproduce**

- Setup Flux for your cluster
- Add Helm Repository for Hashicorp
- Add Helm Release for Vault with >=0.20.0 (see values below)
- Inspect the created StatefulSet and see that `VAULT_CLUSTER_ADDR` environment variable is missing

**Vault logs**

_Cluster address must be set when using raft storage_

**kubectl describe statefulset vault**

<details>
  <summary>Click to see environment variables section</summary>

```text
    Environment:
      HOST_IP:                    (v1:status.hostIP)
      POD_IP:                     (v1:status.podIP)
      VAULT_K8S_POD_NAME:         (v1:metadata.name)
      VAULT_K8S_NAMESPACE:        (v1:metadata.namespace)
      VAULT_ADDR:                http://127.0.0.1:8200
      VAULT_API_ADDR:            http://$(POD_IP):8200
      SKIP_CHOWN:                true
      SKIP_SETCAP:               true
      HOSTNAME:                   (v1:metadata.name)
      VAULT_RAFT_NODE_ID:         (v1:metadata.name)
      HOME:                      /home/vault
      VAULT_LOG_LEVEL:           warn
      VAULT_LOG_FORMAT:          json
      VAULT_SEAL_TYPE:           awskms
      AWS_REGION:                <set to the key 'AWS_REGION' in secret 'vault-auto-unseal'>                Optional: false
      AWS_ACCESS_KEY_ID:         <set to the key 'AWS_ACCESS_KEY_ID' in secret 'vault-auto-unseal'>         Optional: false
      AWS_SECRET_ACCESS_KEY:     <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'vault-auto-unseal'>     Optional: false
      VAULT_AWSKMS_SEAL_KEY_ID:  <set to the key 'VAULT_AWSKMS_SEAL_KEY_ID' in secret 'vault-auto-unseal'>  Optional: false
      AWS_KMS_ENDPOINT:          <set to the key 'AWS_KMS_ENDPOINT' in secret 'vault-auto-unseal'>          Optional: false
```
</details>

**Expected behavior**

Setting the `.server.ha.clusterAddr` value adds the environment variable correctly.

**Environment**

- Kubernetes version: v1.21.0
  - Bare metal (kubeadm)
  - Flux to manage resources
- vault-helm version: 0.21.0

Chart values:

<details>
  <summary>Expand to see values</summary>

```yaml
csi:
  debug: false
  enabled: true
  image:
    pullPolicy: IfNotPresent
  pod:
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  volumeMounts: null
  volumes: null
global:
  openshift: false
  psp:
    enable: false
  tlsDisable: true
injector:
  authPath: auth/kubernetes
  enabled: true
  failurePolicy: Fail
  image:
    pullPolicy: IfNotPresent
  logFormat: json
  metrics:
    enabled: true
  namespaceSelector:
    matchLabels:
      vault-injector: enabled
  objectSelector:
    matchLabels:
      vault-sidecar-injector: enabled
  priorityClassName: system-cluster-critical
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  revokeOnShutdown: false
server:
  auditStorage:
    enabled: true
    mountPath: /vault/audit
    storageClass: dynamic-storage-persistent-nfs
  authDelegator:
    enabled: true
  dataStorage:
    enabled: true
    mountPath: /vault/data
    storageClass: dynamic-storage-persistent-nfs
  dev:
    enabled: false
  enabled: true
  extraEnvironmentVars:
    VAULT_SEAL_TYPE: awskms
  extraSecretEnvironmentVars:
  - envName: AWS_REGION
    secretKey: AWS_REGION
    secretName: vault-auto-unseal
  - envName: AWS_ACCESS_KEY_ID
    secretKey: AWS_ACCESS_KEY_ID
    secretName: vault-auto-unseal
  - envName: AWS_SECRET_ACCESS_KEY
    secretKey: AWS_SECRET_ACCESS_KEY
    secretName: vault-auto-unseal
  - envName: VAULT_AWSKMS_SEAL_KEY_ID
    secretKey: VAULT_AWSKMS_SEAL_KEY_ID
    secretName: vault-auto-unseal
  - envName: AWS_KMS_ENDPOINT
    secretKey: AWS_KMS_ENDPOINT
    secretName: vault-auto-unseal
  ha:
    clusterAddr: https://$(HOSTNAME).vault-internal.vault.svc.cluster.local:8201
    disruptionBudget:
      enabled: true
    enabled: true
    raft:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}
      enabled: true
      setNodeId: true
    replicas: 3
  image:
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  livenessProbe:
    enabled: false
  logFormat: json
  logLevel: warn
  networkPolicy:
    egress: []
    enabled: false
  priorityClassName: system-cluster-critical
  readinessProbe:
    enabled: true
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    enabled: true
  serviceAccount:
    create: false
    name: vault-account
  standalone:
    enabled: false
  updateStrategyType: OnDelete
ui:
  activeVaultPodOnly: true
  enabled: true
  publishNotReadyAddresses: false
```
</details>
