### ISSUE TITLE
Wrong manifests names for CSI provider and external vault

### ISSUE THREAD

**Issue by sthdev** [hashicorp/vault-helm#827]
**Describe the bug**
I want to install only the Vault CSI provider and use it with an external Vault instance. However, authentication with Vault always fails. My `values.yaml` looks like this:

```yaml
global:
  externalVaultAddr: "https://vault.my-domain.com"
server:
  enabled: false
injector:
  enabled: false
csi:
  enabled: true
```

After installing the chart with these values, the names of the generated service accounts seem to be wrong. Calling `helm template vault-csi-provider hashicorp/vault --values values.yaml > out.yaml` yields these manifests (I have added inline comments):

```yaml
---
# Source: vault/templates/csi-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
### This should be 'vault-csi-provider'.
  name: vault-csi-provider-csi-provider
  namespace: flux-system
  labels:
    app.kubernetes.io/name: vault-csi-provider
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
---
# Source: vault/templates/server-serviceaccount.yaml
### IMHO, this manifest should not be generated at all. The server was disabled in the values file.
apiVersion: v1
kind: ServiceAccount
metadata:
### This should be only 'vault'.
  name: vault-csi-provider
  namespace: flux-system
  labels:
    helm.sh/chart: vault-0.23.0
    app.kubernetes.io/name: vault
### This should be only 'vault'.
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
---
# Source: vault/templates/csi-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
### This should be 'vault-csi-provider-clusterrole'.
  name: vault-csi-provider-csi-provider-clusterrole
  labels:
    app.kubernetes.io/name: vault-csi-provider
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
---
# Source: vault/templates/csi-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
### This should be 'vault-csi-provider-clusterrolebinding'.
  name: vault-csi-provider-csi-provider-clusterrolebinding
  labels:
    app.kubernetes.io/name: vault-csi-provider
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
### This should be 'vault-csi-provider-clusterrole'.
  name: vault-csi-provider-csi-provider-clusterrole
subjects:
- kind: ServiceAccount
### This should be 'vault-csi-provider'.
  name: vault-csi-provider-csi-provider
  namespace: flux-system
---
# Source: vault/templates/server-clusterrolebinding.yaml
### IMHO, this manifest should not be generated at all. The server was disabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-csi-provider-server-binding
  labels:
    helm.sh/chart: vault-0.23.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-csi-provider
  namespace: flux-system
---
# Source: vault/templates/csi-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
### This should be 'vault-csi-provider'.
  name: vault-csi-provider-csi-provider
  namespace: flux-system
  labels:
    app.kubernetes.io/name: vault-csi-provider
    app.kubernetes.io/instance: vault-csi-provider
    app.kubernetes.io/managed-by: Helm
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-csi-provider
      app.kubernetes.io/instance: vault-csi-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-csi-provider
        app.kubernetes.io/instance: vault-csi-provider
    spec:
### This should be 'vault-csi-provider'.
      serviceAccountName: vault-csi-provider-csi-provider
      containers:
        - name: vault-csi-provider
          image: "hashicorp/vault-csi-provider:1.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=/provider/vault.sock
            - --debug=false
          env:
            - name: VAULT_ADDR
              value: "https://vault.my-domain.com"
          volumeMounts:
            - name: providervol
              mountPath: "/provider"
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: providervol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
```

The effect is that the service account that the CSI provider pod uses, does not have the `auth-delegator` cluster role. Changing the generated manifests and deploying them manually fixes the problem.

**To Reproduce**
Install or template the chart with the values provided above.

**Expected behavior**
The manifests use the correct service account names so that the CSI provider successfully authenticates with the external vault.

**Environment**
* Kubernetes version: 
  * K3s v1.24.8+k3s1
* vault-helm version:
  * 0.23.0

Chart values:

```yaml
global:
  externalVaultAddr: "https://vault.my-domain.com"
server:
  enabled: false
injector:
  enabled: false
csi:
  enabled: true
```

**Additional context**
n/a
