### ISSUE TITLE
ServiceMonitor endpoint scheme is http when TLS is enabled

### ISSUE THREAD

**Issue by alexandrujieanu** [hashicorp/vault-helm#829]
**Describe the bug**
The ServiceMonitor endpoint has `scheme: http` when TLS is enabled.
The result is that Prometheus gets 400 Bad Request when trying to scrape the TLS endpoint on plain http.

```
global:
  enabled: true
  tlsDisable: false
```

**To Reproduce**
1. Install chart v0.23.0
2. Run vault command `kubectl get servicemonitor vault -o yaml`
3. See error (vault logs, etc.)

```
spec:
  endpoints:
  - interval: 30s
    params:
      format:
      - prometheus
    path: /v1/sys/metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
```

**Expected behavior**
Whenever TLS is enabled, the ServiceMonitor endpoint should have `scheme: https` which works.

Chart values:

```yaml
global:
  enabled: true
  tlsDisable: false

....
serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
      enabled: true
```
