### ISSUE TITLE
Not able to setup vault on two different k8s namespaces

### ISSUE THREAD

**Issue by k-p-ani** [hashicorp/vault-helm#836]
**Describe the bug**
Getting error when trying to deploy vault on two different k8s namespaces.

**To Reproduce**
1. Create a namespace say **demo** in k8s.
2. Install HA enabled vault chart using helm into **demo** namespace.
3. Vault will get deployed successfully
4. Create another namespace say **example** in the same k8s cluster.
5. Install HA enabled vault chart using helm into **example** namespace.
6. This time deployment fail, helm gives below error

rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRoleBinding "vault-server-binding" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "example": current value is "demo"

**Expected behavior**
Vault gets deployed in more than one namespaces in the same k8s cluster.

**Environment**
* Kubernetes version:  1.21
* vault-helm version: 0.23.0

Chart values:

```yaml
global:
  enabled: true
  tlsDisable: true
injector:
  enabled: false
server:
  affinity: ""
  ha:
    enabled: true
    raft:
      config: |-
        ui = true
        plugin_directory = "/vault/plugins"
        listener "tcp" {
           tls_disable = 1
           address = "[::]:8200"
           cluster_address = "[::]:8201"
        }
        storage "raft" {
           path = "/vault/data"
           node_id = "node1"
        }
        disable_mlock = true
        service_registration "kubernetes" {}
      enabled: true
      setNodeId: true
    replicas: 3
  image:
    repository: hashicorp/vault
  ingress:
    activeService: true
    annotations: "cert-manager.io/cluster-issuer: \"zero-ssl\"      \n"
    enabled: true
    hosts:
    - host: x.x.x.com
      paths: []
    ingressClassName: traefik
    pathType: Prefix
    tls:
    - hosts:
      - vault.x.x.x.com
      secretName: vault-ingress-tls
  standalone:
    enabled: false
  volumeMounts:
  - mountPath: /vault/plugins
    name: plugin-directory
  volumes:
  - name: plugin-directory
    persistentVolumeClaim:
      claimName: plugin-pvc
```

**Additional context**

**Comment by tomhjp** [comment]
This isn't really an intended use-case for the helm chart, so we're not looking to add seamless support for this right now. However, there are lots of settings available to disable specific parts of the chart. To work around that specific error, you can use `--set server.authDelegator.enabled=false`.

If you wanted to deploy a second copy of the chart into the _same_ namespace, you would need to disable more. Here's a minimal example of just the bits you'd need to disable:

```yaml
global:
  enabled: false

server:
  enabled: true
  ha:
    enabled: true
    disruptionBudget:
      enabled: false
  authDelegator:
    enabled: false
  serviceAccount:
    create: false
    name: vault
    serviceDiscovery:
      enabled: false
```
