### ISSUE TITLE
Simplify metrics access by supporting an additional service in the chart

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/vault-helm#837]
In an effort to simplify metrics access it would be nice if the template supported an option to enable a service for metrics. This way consumers of the chart could use `unauthenticated_metrics_access = "true"` on a different listener that was not going to be exposed via ingress. In my use-case I want to expose a service http://vault-metrics.vault-enterprise:9200 to my Datadog agents for the Vault integration.

**Describe the solution you'd like**

Something like this may fit in this section of the values:

```yaml
  # Enables a headless service to be used by the Vault Statefulset
  service:
    enabled: true
    # Enable or disable the vault-active service, which selects Vault pods that
    # have labelled themselves as the cluster leader with `vault-active: "true"`
    active:
      enabled: true
    # Enable or disable the vault-standby service, which selects Vault pods that
    # have labelled themselves as a cluster follower with `vault-active: "false"`
    standby:
      enabled: true
    # Enable or disable the vault-metrics service, which expose unauthenticated_metrics_access
    # on a port and service not exposed by ingress.
    metrics:
       enabled: true
       port: 9200 
    # If enabled, the service selectors will include `app.kubernetes.io/instance: {{ .Release.Name }}`
    # When disabled, services may select Vault pods not deployed from the chart.
    # Does not affect the headless vault-internal service with `ClusterIP: None`
    instanceSelector:
      enabled: true
    # clusterIP controls whether a Cluster IP address is attached to the
    # Vault service within Kubernetes.  By default, the Vault service will
    # be given a Cluster IP address, set to None to disable.  When disabled
    # Kubernetes will create a "headless" service.  Headless services can be
    # used to communicate with pods directly through DNS instead of a round-robin
    # load balancer.
    # clusterIP: None
```
**Describe alternatives you've considered**

Right now I add my own service:

```hcl
# Kubernetes Service Resource
# https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service_v1

resource "kubernetes_service_v1" "vault_metrics" {
  metadata {
    name      = "vault-metrics"
    namespace = kubernetes_namespace_v1.vault_enterprise.metadata[0].name
  }

  spec {
    cluster_ip = "None"

    selector = {
      "app.kubernetes.io/instance" = "vault"
      "app.kubernetes.io/name"     = "vault"
      "component"                  = "server"
    }

    port {
      name        = "metrics"
      port        = 9200
      target_port = 9200
    }
  }
}
```

And setup my listeners like this in the chart:

```hcl
# Helm Release
# https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

resource "helm_release" "vault_enterprise" {
  chart      = "vault"
  name       = "vault"
  namespace  = kubernetes_namespace_v1.vault_enterprise.metadata[0].name
  repository = "https://helm.releases.hashicorp.com"
  timeout    = 600

  set {
    name  = "server.ha.raft.config"
    value = <<EOF
        ui = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/tls/vault.crt"
          tls_client_ca_file = "/vault/tls/vault.ca"
          tls_key_file  = "/vault/tls/vault.key"

        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.crt"
            leader_client_cert_file = "/vault/tls/vault.ca"
            leader_client_key_file = "/vault/tls/vault.key"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.crt"
            leader_client_cert_file = "/vault/tls/vault.ca"
            leader_client_key_file = "/vault/tls/vault.key"
          }

          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_ca_cert_file = "/vault/tls/vault.crt"
            leader_client_cert_file = "/vault/tls/vault.ca"
            leader_client_key_file = "/vault/tls/vault.key"
          }
        }

        service_registration "kubernetes" {}

        seal "gcpckms" {
          project     = "${local.regional_infra.project_id}"
          region      = "${var.region}"
          key_ring    = "services-${var.region}"
          crypto_key  = "vault-enterprise-unseal"
        }

        listener "tcp" {
          address = "[::]:9200"
          tls_disable = "true"

          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }

        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }
        EOF
  }
```

**Additional context**

If there is a better way to do this already please let me know, thanks!
