### ISSUE TITLE
No way to associate PVC to all pods in HA mode with 3 replica

### ISSUE THREAD

**Issue by k-p-ani** [hashicorp/vault-helm#845]
**Describe the bug**
In my values.yaml HA mode is enabled (3 replicas ) and storage used is raft storage. I defined **volumeMounts** and corresponding **volumes** to copy my secret plugin (custom)  as show below under **server** section
```
server:
   volumes:
      - name: plugin-directory
        persistentVolumeClaim:
           claimName: plugin-pvc
   volumeMounts:
      - name: plugin-directory
        mountPath: "/vault/plugins" 
```
 When vault is installed first vault pod **vault-0** comes up properly as it is able to mount the path /vault/plugins using PVC plugin-pvc. But second  and third vault pod fails giving error.
Multi-Attach error for volume "pvc-5716bcde-cc30-42fb-8482-d3e3ec9e4abd" Volume is already used by pod(s) vault-0 

**To Reproduce**
1. In value.yaml, enable HA with 3 replicas and define volumes and volumeMounts as above
2. Install vault using helm
3. Only one pod will be in **running** status, rest two will remain in **ContainerCreating** status
4. Run command kubectl describe pod vault-1 -n <name-space>
Under events you will see error
Multi-Attach error for volume "pvc-5716bcde-cc30-42fb-8482-d3e3ec9e4abd" Volume is already used by pod(s) vault-0 

**Expected behavior**
A way to define PVC for all the node like currently helm does by creating  PVC **data-vault-x**, where **x** stands for each replica
