### ISSUE TITLE
ValidationError(Ingress.spec.rules[0].http.paths[0].backend.service.port.number): invalid type for io.k8s.api.networking.v1.ServiceBackendPort.number: got "string", expected "integer"

### ISSUE THREAD

**Issue by ladung** [hashicorp/vault-helm#864]
Value customs is 
```
extraPaths: 
    - path: /
      backend:
        service:
          name: ssl-redirect
          port:
            number: use-annotation
```

And i have a problem
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/43999277/229400456-96a4eca6-0db7-4743-9940-4e5eed79a450.png">
