### ISSUE TITLE
Prometheus rules has the wrong data type

### ISSUE THREAD

**Issue by mgriffin13** [hashicorp/vault-helm#885]
**Describe the bug**
When attempting to inject Prometheus rules via my overrides-values.yaml file, I get a warning. 

```bash
coalesce.go:220: warning: cannot overwrite table with non table for vault.serverTelemetry.prometheusRules.rules (map[])
```

**To Reproduce**
1. Create `override-values.yml` file
2. Execute helm installation command with `--values override-values.yml`
3. See error at command line

**Expected behavior**
Helm to execute without warnings or errors.

**Environment**
```bash
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

`override-values.yml`

```yaml
# Configure Prometheus
serverTelemetry:
  serviceMonitor:
    enabled: true

  prometheusRules:
    enabled: true
    rules:
      - alert: vault-HighResponseTime
        annotations:
          message: The response time of Vault is over 500ms on average over the last 5 minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
        for: 5m
        labels:
          severity: warning
      - alert: vault-HighResponseTime
        annotations:
          message: The response time of Vault is over 1s on average over the last 5 minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
        for: 5m
        labels:
          severity: critical
```

**Additional context**
I believe the bug is at https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L1201, where `rules: {}` is defined as a map, but the examples show a list data structure.
