### ISSUE TITLE
vault-server statefulset deployed when only vault-injector is enabled.

### ISSUE THREAD

**Issue by afer4152** [hashicorp/vault-helm#895]
**Describe the bug**
vault-server stateful set deployed when only vault-injector is enabled. (Source: templates/server-statefulset.yaml)

**To Reproduce**
1. Install chart
2. helm dependency update
3. helm template

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (EKS 1.23)
* vault-helm version: 0.23.0

Chart values:
```yaml
apiVersion: v2
name: vault-injector
version: 1.0.0
dependencies:
  - name: vault
    version: 0.23.0
    repository: https://helm.releases.hashicorp.com
```

```yaml
vault-injector:
  global:
    enabled: false
    externalVaultAddr: https://<>
  injector:
    enabled: true
```

**Comment by tomhjp** [comment]
I can't reproduce - this shows up nothing for me:

```shell-session
$ git checkout v0.23.0
# ...
$ echo "$(helm template vault . -f- <<EOF
global:
  enabled: false
  externalVaultAddr: https://<>
injector:
  enabled: true
EOF
)" | grep StatefulSet
```

**Comment by afer4152** [comment]
This is got sorted. `vault-injector` updated as `vault`

```
vault:
  global:
    enabled: false
    externalVaultAddr: https://<>
  injector:
    enabled: true
```
