### ISSUE TITLE
server.extraLabels missing on statefulset

### ISSUE THREAD

**Issue by hameno** [hashicorp/vault-helm#911]
**Describe the bug**
Setting server.extraLabels only applies labels to pods and not to the statefulset itself.

**To Reproduce**
1. Install chart with server.extraLabels set
2. Look at statefulset

**Expected behavior**
Labels should be applied to the statefulset

**Environment**
* Kubernetes version: EKS 1.24
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.):
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version: 0.24.1

Chart values:

```yaml
# Paste your user-supplied values here (`helm get values <release>`).
# Be sure to scrub any sensitive values!
server:
  extraLabels:
    tags.datadoghq.com/service: vault
```

**Additional context**
We're setting up Datadog and the statefulset should be labelled aswell.
