### ISSUE TITLE
PV not being created upon provisioning - resulting in Vault Pod being stuck in pending state

### ISSUE THREAD

**Issue by BJWRD** [hashicorp/vault-helm#936]
**Describe the bug**
Upon Helm deployment using the values referenced below, there doesn't appear to be a PV being deployed alongside the PVC (not bound). This is resulting in the Vault pod being stuck in a pending state. 

**To Reproduce**
Any deployment including the following Helm values -

```   
values:
    server:
      ingress:
        enabled: true
        hosts:
          - host: hostname.com
      dataStorage:
        enabled: true
        # Size of the PVC created
        size: 20Gi
        storageClass: gp2
        mountPath: "/vault/data"
      prometheusRules:
        enabled: true
```
**Other useful info:**

Pod - `vault-0`
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  98s   default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition
```
PVC  - `data-vault-0`
``` 
kubectl describe pvc data-vault-0 -n vault
Name:          data-vault-0
Namespace:     vault
StorageClass:  gp2
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/instance=vault
               app.kubernetes.io/name=vault
               component=server
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: redacted
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       vault-0
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  WaitForFirstConsumer  10m                   persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  4m14s (x25 over 10m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```
PV 
```
 kubectl get pv -n vault
No resources found
```
**Expected behavior**
Vault PV being provisioned during the Helm deployment. Resulting in the Vault pod `vault-0` not being stuck in `pending` status and being accessible.

**Environment**
EKS - 1.25

vault-helm version:
  version: "0.25.0"

Chart values:

```   
values:
    server:
      ingress:
        enabled: true
        hosts:
          - host: hostname.com
      dataStorage:
        enabled: true
        # Size of the PVC created
        size: 20Gi
        storageClass: gp2
        mountPath: "/vault/data"
      prometheusRules:
        enabled: true
```
