### ISSUE TITLE
Vault Injector NetworkPolicy requires additional `from` rules in OCP 4.13

### ISSUE THREAD

**Issue by komish** [hashicorp/vault-helm#953]
_This is a copy of the issue created https://github.com/openshift-helm-charts/charts/issues/934. That issue will be closed in favor of this one._

**Describe the bug**

We had issues in our testing with vault's MutatingWebhookConfiguration not being accessible by kube-apiserver in OCP 4.13. Per my testing, this is just because the NetworkPolicy that's created needs an extra match criteria.

The policy looks like this in your latest chart:
https://github.com/openshift-helm-charts/charts/blob/main/charts/partners/hashicorp/vault/0.24.0/src/templates/injector-network-policy.yaml

The from items needs to include an additional entry allowing host network workloads to reach it.

```yaml
...
spec:
  podSelector:
    ... removed for brevity ...
  ingress:
    - from:
        - namespaceSelector: {}
        - namespaceSelector:      # add this and the following lines
            matchLabels:
              policy-group.network.openshift.io/host-network: ""
...
```

This is documented here:
https://docs.openshift.com/container-platform/4.13/networking/network_policy/about-network-policy.html#nw-networkpolicy-allow-from-hostnetwork_about-network-policy

We discovered it when chart-testing would run. The webhook would be live and the chart-test would immediately fail because the pod it creates would fail at admission (due to the webhook being inaccessible from the kube-apiserver).

**To Reproduce**
1. Run chart-testing against the existing chart on an OCP 4.13 cluster.

**Expected behavior**
chart-testing would pass

**Environment**
OCP 4.13

**Additional context**
