### ISSUE TITLE
Support StatefulSet PVC retention feature

### ISSUE THREAD

**Issue by alemuro** [hashicorp/vault-helm#964]
#### Feature Description

Kubernetes released a feature for automatically purging PVCs when the StatefulSet controller removes one of the pods. 

This issue is for asking to expose this configuration in the Helm chart so we can parametrise it and set the proper value depending on the environment. 

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

According to the documentation what we need is to add the following lines to the StatefulSet, and to parametrise it with Helm chart variables:

```yaml
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
...
```

#### Use Case(s)

This is useful when testing the chart, as in those cases we want to create it/remove it, but the PVCs are not removed. This feature would allow us to remove PVCs on test environments but to retain them on production.
