### ISSUE TITLE
 An error occurred in the init container(Operation not permitted)

### ISSUE THREAD

**Issue by sdYoo** [hashicorp/vault-helm#973]
**Describe the bug**
After executing the helm chart, the following error occurs when running the init container.

➜  ~ kc logs -f vault-0 -c busybox -n security
chown: /vault/logs: Operation not permitted
chown: /vault/logs: Operation not permitted

**To Reproduce**
1. Install chart
2. Run vault command
3. See error (vault logs, etc.)

vault-0                                                0/1     Init:CrashLoopBackOff   5 (60s ago)   4m13s   10.252.6.12     node01       <none>           <none>
vault-1                                                0/1     Init:CrashLoopBackOff   5 (65s ago)   4m11s   10.252.26.87    node02       <none>           <none>

Other useful info to include: vault pod logs, `kubectl describe statefulset vault` and `kubectl get statefulset vault -o yaml` output

**Expected behavior**

**Environment**
* Kubernetes version: 
  * Distribution or cloud vendor (OpenShift, EKS, GKE, AKS, etc.):
  * Other configuration options or runtime services (istio, etc.):
* vault-helm version:
apiVersion: v2
name: vault
version: 0.24.1
appVersion: 1.13.1

Chart values:

```yaml

values.yaml

server:
  # Configure the logging format for the Vault server.
  # Supported log formats include: standard, json
  logFormat: "json"

  extraInitContainers:
  - name: busybox
    image: "docker-hub-custom.com/finalspy/busybox-curl-jq"
    command: [ "sh", "-c", "chown -R 1000:1000 /vault/logs" ]
    volumeMounts:
      - name: logs
        mountPath: /vault/logs
```

**Additional context**
